// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/app/dynamic/v1/dynamic.proto

package com.bapis.bilibili.app.dynamic.v1;

/**
 * <pre>
 * 动态同城物料cover模块
 * </pre>
 *
 * Protobuf type {@code bilibili.app.dynamic.v1.DynOurCityModuleCover}
 */
public final class DynOurCityModuleCover extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bilibili.app.dynamic.v1.DynOurCityModuleCover)
    DynOurCityModuleCoverOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DynOurCityModuleCover.newBuilder() to construct.
  private DynOurCityModuleCover(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DynOurCityModuleCover() {
    covers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    coverLeftText1_ = "";
    coverLeftText2_ = "";
    coverLeftText3_ = "";
    badge_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new DynOurCityModuleCover();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DynOurCityModuleCover(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              covers_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            covers_.add(s);
            break;
          }
          case 16: {

            style_ = input.readInt32();
            break;
          }
          case 24: {

            coverLeftIcon1_ = input.readInt32();
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            coverLeftText1_ = s;
            break;
          }
          case 40: {

            coverLeftIcon2_ = input.readInt32();
            break;
          }
          case 50: {
            String s = input.readStringRequireUtf8();

            coverLeftText2_ = s;
            break;
          }
          case 58: {
            String s = input.readStringRequireUtf8();

            coverLeftText3_ = s;
            break;
          }
          case 66: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              badge_ = new java.util.ArrayList<VideoBadge>();
              mutable_bitField0_ |= 0x00000002;
            }
            badge_.add(
                input.readMessage(VideoBadge.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        covers_ = covers_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        badge_ = java.util.Collections.unmodifiableList(badge_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return DynamicOuterClass.internal_static_bilibili_app_dynamic_v1_DynOurCityModuleCover_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return DynamicOuterClass.internal_static_bilibili_app_dynamic_v1_DynOurCityModuleCover_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            DynOurCityModuleCover.class, Builder.class);
  }

  public static final int COVERS_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList covers_;
  /**
   * <pre>
   * 封面图 单图样式取第一个元素
   * </pre>
   *
   * <code>repeated string covers = 1;</code>
   * @return A list containing the covers.
   */
  public com.google.protobuf.ProtocolStringList
      getCoversList() {
    return covers_;
  }
  /**
   * <pre>
   * 封面图 单图样式取第一个元素
   * </pre>
   *
   * <code>repeated string covers = 1;</code>
   * @return The count of covers.
   */
  public int getCoversCount() {
    return covers_.size();
  }
  /**
   * <pre>
   * 封面图 单图样式取第一个元素
   * </pre>
   *
   * <code>repeated string covers = 1;</code>
   * @param index The index of the element to return.
   * @return The covers at the given index.
   */
  public String getCovers(int index) {
    return covers_.get(index);
  }
  /**
   * <pre>
   * 封面图 单图样式取第一个元素
   * </pre>
   *
   * <code>repeated string covers = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the covers at the given index.
   */
  public com.google.protobuf.ByteString
      getCoversBytes(int index) {
    return covers_.getByteString(index);
  }

  public static final int STYLE_FIELD_NUMBER = 2;
  private int style_;
  /**
   * <pre>
   * 封面样式 1-横图 2-竖图 3-方图
   * </pre>
   *
   * <code>int32 style = 2;</code>
   * @return The style.
   */
  @Override
  public int getStyle() {
    return style_;
  }

  public static final int COVER_LEFT_ICON_1_FIELD_NUMBER = 3;
  private int coverLeftIcon1_;
  /**
   * <pre>
   * 视频封面展示项图标 1
   * </pre>
   *
   * <code>int32 cover_left_icon_1 = 3;</code>
   * @return The coverLeftIcon1.
   */
  @Override
  public int getCoverLeftIcon1() {
    return coverLeftIcon1_;
  }

  public static final int COVER_LEFT_TEXT_1_FIELD_NUMBER = 4;
  private volatile Object coverLeftText1_;
  /**
   * <pre>
   * 视频封面展示项 1
   * </pre>
   *
   * <code>string cover_left_text_1 = 4;</code>
   * @return The coverLeftText1.
   */
  @Override
  public String getCoverLeftText1() {
    Object ref = coverLeftText1_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      coverLeftText1_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 视频封面展示项 1
   * </pre>
   *
   * <code>string cover_left_text_1 = 4;</code>
   * @return The bytes for coverLeftText1.
   */
  @Override
  public com.google.protobuf.ByteString
      getCoverLeftText1Bytes() {
    Object ref = coverLeftText1_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      coverLeftText1_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COVER_LEFT_ICON_2_FIELD_NUMBER = 5;
  private int coverLeftIcon2_;
  /**
   * <pre>
   * 视频封面展示项图标 2
   * </pre>
   *
   * <code>int32 cover_left_icon_2 = 5;</code>
   * @return The coverLeftIcon2.
   */
  @Override
  public int getCoverLeftIcon2() {
    return coverLeftIcon2_;
  }

  public static final int COVER_LEFT_TEXT_2_FIELD_NUMBER = 6;
  private volatile Object coverLeftText2_;
  /**
   * <pre>
   * 视频封面展示项 2
   * </pre>
   *
   * <code>string cover_left_text_2 = 6;</code>
   * @return The coverLeftText2.
   */
  @Override
  public String getCoverLeftText2() {
    Object ref = coverLeftText2_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      coverLeftText2_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 视频封面展示项 2
   * </pre>
   *
   * <code>string cover_left_text_2 = 6;</code>
   * @return The bytes for coverLeftText2.
   */
  @Override
  public com.google.protobuf.ByteString
      getCoverLeftText2Bytes() {
    Object ref = coverLeftText2_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      coverLeftText2_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COVER_LEFT_TEXT_3_FIELD_NUMBER = 7;
  private volatile Object coverLeftText3_;
  /**
   * <pre>
   * 封面视频展示项 3
   * </pre>
   *
   * <code>string cover_left_text_3 = 7;</code>
   * @return The coverLeftText3.
   */
  @Override
  public String getCoverLeftText3() {
    Object ref = coverLeftText3_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      coverLeftText3_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 封面视频展示项 3
   * </pre>
   *
   * <code>string cover_left_text_3 = 7;</code>
   * @return The bytes for coverLeftText3.
   */
  @Override
  public com.google.protobuf.ByteString
      getCoverLeftText3Bytes() {
    Object ref = coverLeftText3_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      coverLeftText3_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BADGE_FIELD_NUMBER = 8;
  private java.util.List<VideoBadge> badge_;
  /**
   * <pre>
   * 角标
   * </pre>
   *
   * <code>repeated .bilibili.app.dynamic.v1.VideoBadge badge = 8;</code>
   */
  @Override
  public java.util.List<VideoBadge> getBadgeList() {
    return badge_;
  }
  /**
   * <pre>
   * 角标
   * </pre>
   *
   * <code>repeated .bilibili.app.dynamic.v1.VideoBadge badge = 8;</code>
   */
  @Override
  public java.util.List<? extends VideoBadgeOrBuilder>
      getBadgeOrBuilderList() {
    return badge_;
  }
  /**
   * <pre>
   * 角标
   * </pre>
   *
   * <code>repeated .bilibili.app.dynamic.v1.VideoBadge badge = 8;</code>
   */
  @Override
  public int getBadgeCount() {
    return badge_.size();
  }
  /**
   * <pre>
   * 角标
   * </pre>
   *
   * <code>repeated .bilibili.app.dynamic.v1.VideoBadge badge = 8;</code>
   */
  @Override
  public VideoBadge getBadge(int index) {
    return badge_.get(index);
  }
  /**
   * <pre>
   * 角标
   * </pre>
   *
   * <code>repeated .bilibili.app.dynamic.v1.VideoBadge badge = 8;</code>
   */
  @Override
  public VideoBadgeOrBuilder getBadgeOrBuilder(
      int index) {
    return badge_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < covers_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, covers_.getRaw(i));
    }
    if (style_ != 0) {
      output.writeInt32(2, style_);
    }
    if (coverLeftIcon1_ != 0) {
      output.writeInt32(3, coverLeftIcon1_);
    }
    if (!getCoverLeftText1Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, coverLeftText1_);
    }
    if (coverLeftIcon2_ != 0) {
      output.writeInt32(5, coverLeftIcon2_);
    }
    if (!getCoverLeftText2Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, coverLeftText2_);
    }
    if (!getCoverLeftText3Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, coverLeftText3_);
    }
    for (int i = 0; i < badge_.size(); i++) {
      output.writeMessage(8, badge_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < covers_.size(); i++) {
        dataSize += computeStringSizeNoTag(covers_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getCoversList().size();
    }
    if (style_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, style_);
    }
    if (coverLeftIcon1_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, coverLeftIcon1_);
    }
    if (!getCoverLeftText1Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, coverLeftText1_);
    }
    if (coverLeftIcon2_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, coverLeftIcon2_);
    }
    if (!getCoverLeftText2Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, coverLeftText2_);
    }
    if (!getCoverLeftText3Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, coverLeftText3_);
    }
    for (int i = 0; i < badge_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, badge_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof DynOurCityModuleCover)) {
      return super.equals(obj);
    }
    DynOurCityModuleCover other = (DynOurCityModuleCover) obj;

    if (!getCoversList()
        .equals(other.getCoversList())) return false;
    if (getStyle()
        != other.getStyle()) return false;
    if (getCoverLeftIcon1()
        != other.getCoverLeftIcon1()) return false;
    if (!getCoverLeftText1()
        .equals(other.getCoverLeftText1())) return false;
    if (getCoverLeftIcon2()
        != other.getCoverLeftIcon2()) return false;
    if (!getCoverLeftText2()
        .equals(other.getCoverLeftText2())) return false;
    if (!getCoverLeftText3()
        .equals(other.getCoverLeftText3())) return false;
    if (!getBadgeList()
        .equals(other.getBadgeList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCoversCount() > 0) {
      hash = (37 * hash) + COVERS_FIELD_NUMBER;
      hash = (53 * hash) + getCoversList().hashCode();
    }
    hash = (37 * hash) + STYLE_FIELD_NUMBER;
    hash = (53 * hash) + getStyle();
    hash = (37 * hash) + COVER_LEFT_ICON_1_FIELD_NUMBER;
    hash = (53 * hash) + getCoverLeftIcon1();
    hash = (37 * hash) + COVER_LEFT_TEXT_1_FIELD_NUMBER;
    hash = (53 * hash) + getCoverLeftText1().hashCode();
    hash = (37 * hash) + COVER_LEFT_ICON_2_FIELD_NUMBER;
    hash = (53 * hash) + getCoverLeftIcon2();
    hash = (37 * hash) + COVER_LEFT_TEXT_2_FIELD_NUMBER;
    hash = (53 * hash) + getCoverLeftText2().hashCode();
    hash = (37 * hash) + COVER_LEFT_TEXT_3_FIELD_NUMBER;
    hash = (53 * hash) + getCoverLeftText3().hashCode();
    if (getBadgeCount() > 0) {
      hash = (37 * hash) + BADGE_FIELD_NUMBER;
      hash = (53 * hash) + getBadgeList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static DynOurCityModuleCover parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DynOurCityModuleCover parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DynOurCityModuleCover parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DynOurCityModuleCover parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DynOurCityModuleCover parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DynOurCityModuleCover parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DynOurCityModuleCover parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DynOurCityModuleCover parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static DynOurCityModuleCover parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static DynOurCityModuleCover parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static DynOurCityModuleCover parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DynOurCityModuleCover parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(DynOurCityModuleCover prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 动态同城物料cover模块
   * </pre>
   *
   * Protobuf type {@code bilibili.app.dynamic.v1.DynOurCityModuleCover}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bilibili.app.dynamic.v1.DynOurCityModuleCover)
      DynOurCityModuleCoverOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DynamicOuterClass.internal_static_bilibili_app_dynamic_v1_DynOurCityModuleCover_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DynamicOuterClass.internal_static_bilibili_app_dynamic_v1_DynOurCityModuleCover_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DynOurCityModuleCover.class, Builder.class);
    }

    // Construct using com.bapis.bilibili.app.dynamic.v1.DynOurCityModuleCover.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBadgeFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      covers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      style_ = 0;

      coverLeftIcon1_ = 0;

      coverLeftText1_ = "";

      coverLeftIcon2_ = 0;

      coverLeftText2_ = "";

      coverLeftText3_ = "";

      if (badgeBuilder_ == null) {
        badge_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        badgeBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return DynamicOuterClass.internal_static_bilibili_app_dynamic_v1_DynOurCityModuleCover_descriptor;
    }

    @Override
    public DynOurCityModuleCover getDefaultInstanceForType() {
      return DynOurCityModuleCover.getDefaultInstance();
    }

    @Override
    public DynOurCityModuleCover build() {
      DynOurCityModuleCover result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public DynOurCityModuleCover buildPartial() {
      DynOurCityModuleCover result = new DynOurCityModuleCover(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        covers_ = covers_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.covers_ = covers_;
      result.style_ = style_;
      result.coverLeftIcon1_ = coverLeftIcon1_;
      result.coverLeftText1_ = coverLeftText1_;
      result.coverLeftIcon2_ = coverLeftIcon2_;
      result.coverLeftText2_ = coverLeftText2_;
      result.coverLeftText3_ = coverLeftText3_;
      if (badgeBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          badge_ = java.util.Collections.unmodifiableList(badge_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.badge_ = badge_;
      } else {
        result.badge_ = badgeBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof DynOurCityModuleCover) {
        return mergeFrom((DynOurCityModuleCover)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(DynOurCityModuleCover other) {
      if (other == DynOurCityModuleCover.getDefaultInstance()) return this;
      if (!other.covers_.isEmpty()) {
        if (covers_.isEmpty()) {
          covers_ = other.covers_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureCoversIsMutable();
          covers_.addAll(other.covers_);
        }
        onChanged();
      }
      if (other.getStyle() != 0) {
        setStyle(other.getStyle());
      }
      if (other.getCoverLeftIcon1() != 0) {
        setCoverLeftIcon1(other.getCoverLeftIcon1());
      }
      if (!other.getCoverLeftText1().isEmpty()) {
        coverLeftText1_ = other.coverLeftText1_;
        onChanged();
      }
      if (other.getCoverLeftIcon2() != 0) {
        setCoverLeftIcon2(other.getCoverLeftIcon2());
      }
      if (!other.getCoverLeftText2().isEmpty()) {
        coverLeftText2_ = other.coverLeftText2_;
        onChanged();
      }
      if (!other.getCoverLeftText3().isEmpty()) {
        coverLeftText3_ = other.coverLeftText3_;
        onChanged();
      }
      if (badgeBuilder_ == null) {
        if (!other.badge_.isEmpty()) {
          if (badge_.isEmpty()) {
            badge_ = other.badge_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureBadgeIsMutable();
            badge_.addAll(other.badge_);
          }
          onChanged();
        }
      } else {
        if (!other.badge_.isEmpty()) {
          if (badgeBuilder_.isEmpty()) {
            badgeBuilder_.dispose();
            badgeBuilder_ = null;
            badge_ = other.badge_;
            bitField0_ = (bitField0_ & ~0x00000002);
            badgeBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBadgeFieldBuilder() : null;
          } else {
            badgeBuilder_.addAllMessages(other.badge_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      DynOurCityModuleCover parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (DynOurCityModuleCover) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList covers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureCoversIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        covers_ = new com.google.protobuf.LazyStringArrayList(covers_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * 封面图 单图样式取第一个元素
     * </pre>
     *
     * <code>repeated string covers = 1;</code>
     * @return A list containing the covers.
     */
    public com.google.protobuf.ProtocolStringList
        getCoversList() {
      return covers_.getUnmodifiableView();
    }
    /**
     * <pre>
     * 封面图 单图样式取第一个元素
     * </pre>
     *
     * <code>repeated string covers = 1;</code>
     * @return The count of covers.
     */
    public int getCoversCount() {
      return covers_.size();
    }
    /**
     * <pre>
     * 封面图 单图样式取第一个元素
     * </pre>
     *
     * <code>repeated string covers = 1;</code>
     * @param index The index of the element to return.
     * @return The covers at the given index.
     */
    public String getCovers(int index) {
      return covers_.get(index);
    }
    /**
     * <pre>
     * 封面图 单图样式取第一个元素
     * </pre>
     *
     * <code>repeated string covers = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the covers at the given index.
     */
    public com.google.protobuf.ByteString
        getCoversBytes(int index) {
      return covers_.getByteString(index);
    }
    /**
     * <pre>
     * 封面图 单图样式取第一个元素
     * </pre>
     *
     * <code>repeated string covers = 1;</code>
     * @param index The index to set the value at.
     * @param value The covers to set.
     * @return This builder for chaining.
     */
    public Builder setCovers(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCoversIsMutable();
      covers_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 封面图 单图样式取第一个元素
     * </pre>
     *
     * <code>repeated string covers = 1;</code>
     * @param value The covers to add.
     * @return This builder for chaining.
     */
    public Builder addCovers(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCoversIsMutable();
      covers_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 封面图 单图样式取第一个元素
     * </pre>
     *
     * <code>repeated string covers = 1;</code>
     * @param values The covers to add.
     * @return This builder for chaining.
     */
    public Builder addAllCovers(
        Iterable<String> values) {
      ensureCoversIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, covers_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 封面图 单图样式取第一个元素
     * </pre>
     *
     * <code>repeated string covers = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCovers() {
      covers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 封面图 单图样式取第一个元素
     * </pre>
     *
     * <code>repeated string covers = 1;</code>
     * @param value The bytes of the covers to add.
     * @return This builder for chaining.
     */
    public Builder addCoversBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureCoversIsMutable();
      covers_.add(value);
      onChanged();
      return this;
    }

    private int style_ ;
    /**
     * <pre>
     * 封面样式 1-横图 2-竖图 3-方图
     * </pre>
     *
     * <code>int32 style = 2;</code>
     * @return The style.
     */
    @Override
    public int getStyle() {
      return style_;
    }
    /**
     * <pre>
     * 封面样式 1-横图 2-竖图 3-方图
     * </pre>
     *
     * <code>int32 style = 2;</code>
     * @param value The style to set.
     * @return This builder for chaining.
     */
    public Builder setStyle(int value) {
      
      style_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 封面样式 1-横图 2-竖图 3-方图
     * </pre>
     *
     * <code>int32 style = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStyle() {
      
      style_ = 0;
      onChanged();
      return this;
    }

    private int coverLeftIcon1_ ;
    /**
     * <pre>
     * 视频封面展示项图标 1
     * </pre>
     *
     * <code>int32 cover_left_icon_1 = 3;</code>
     * @return The coverLeftIcon1.
     */
    @Override
    public int getCoverLeftIcon1() {
      return coverLeftIcon1_;
    }
    /**
     * <pre>
     * 视频封面展示项图标 1
     * </pre>
     *
     * <code>int32 cover_left_icon_1 = 3;</code>
     * @param value The coverLeftIcon1 to set.
     * @return This builder for chaining.
     */
    public Builder setCoverLeftIcon1(int value) {
      
      coverLeftIcon1_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 视频封面展示项图标 1
     * </pre>
     *
     * <code>int32 cover_left_icon_1 = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCoverLeftIcon1() {
      
      coverLeftIcon1_ = 0;
      onChanged();
      return this;
    }

    private Object coverLeftText1_ = "";
    /**
     * <pre>
     * 视频封面展示项 1
     * </pre>
     *
     * <code>string cover_left_text_1 = 4;</code>
     * @return The coverLeftText1.
     */
    public String getCoverLeftText1() {
      Object ref = coverLeftText1_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        coverLeftText1_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 视频封面展示项 1
     * </pre>
     *
     * <code>string cover_left_text_1 = 4;</code>
     * @return The bytes for coverLeftText1.
     */
    public com.google.protobuf.ByteString
        getCoverLeftText1Bytes() {
      Object ref = coverLeftText1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        coverLeftText1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 视频封面展示项 1
     * </pre>
     *
     * <code>string cover_left_text_1 = 4;</code>
     * @param value The coverLeftText1 to set.
     * @return This builder for chaining.
     */
    public Builder setCoverLeftText1(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      coverLeftText1_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 视频封面展示项 1
     * </pre>
     *
     * <code>string cover_left_text_1 = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCoverLeftText1() {
      
      coverLeftText1_ = getDefaultInstance().getCoverLeftText1();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 视频封面展示项 1
     * </pre>
     *
     * <code>string cover_left_text_1 = 4;</code>
     * @param value The bytes for coverLeftText1 to set.
     * @return This builder for chaining.
     */
    public Builder setCoverLeftText1Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      coverLeftText1_ = value;
      onChanged();
      return this;
    }

    private int coverLeftIcon2_ ;
    /**
     * <pre>
     * 视频封面展示项图标 2
     * </pre>
     *
     * <code>int32 cover_left_icon_2 = 5;</code>
     * @return The coverLeftIcon2.
     */
    @Override
    public int getCoverLeftIcon2() {
      return coverLeftIcon2_;
    }
    /**
     * <pre>
     * 视频封面展示项图标 2
     * </pre>
     *
     * <code>int32 cover_left_icon_2 = 5;</code>
     * @param value The coverLeftIcon2 to set.
     * @return This builder for chaining.
     */
    public Builder setCoverLeftIcon2(int value) {
      
      coverLeftIcon2_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 视频封面展示项图标 2
     * </pre>
     *
     * <code>int32 cover_left_icon_2 = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCoverLeftIcon2() {
      
      coverLeftIcon2_ = 0;
      onChanged();
      return this;
    }

    private Object coverLeftText2_ = "";
    /**
     * <pre>
     * 视频封面展示项 2
     * </pre>
     *
     * <code>string cover_left_text_2 = 6;</code>
     * @return The coverLeftText2.
     */
    public String getCoverLeftText2() {
      Object ref = coverLeftText2_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        coverLeftText2_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 视频封面展示项 2
     * </pre>
     *
     * <code>string cover_left_text_2 = 6;</code>
     * @return The bytes for coverLeftText2.
     */
    public com.google.protobuf.ByteString
        getCoverLeftText2Bytes() {
      Object ref = coverLeftText2_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        coverLeftText2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 视频封面展示项 2
     * </pre>
     *
     * <code>string cover_left_text_2 = 6;</code>
     * @param value The coverLeftText2 to set.
     * @return This builder for chaining.
     */
    public Builder setCoverLeftText2(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      coverLeftText2_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 视频封面展示项 2
     * </pre>
     *
     * <code>string cover_left_text_2 = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCoverLeftText2() {
      
      coverLeftText2_ = getDefaultInstance().getCoverLeftText2();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 视频封面展示项 2
     * </pre>
     *
     * <code>string cover_left_text_2 = 6;</code>
     * @param value The bytes for coverLeftText2 to set.
     * @return This builder for chaining.
     */
    public Builder setCoverLeftText2Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      coverLeftText2_ = value;
      onChanged();
      return this;
    }

    private Object coverLeftText3_ = "";
    /**
     * <pre>
     * 封面视频展示项 3
     * </pre>
     *
     * <code>string cover_left_text_3 = 7;</code>
     * @return The coverLeftText3.
     */
    public String getCoverLeftText3() {
      Object ref = coverLeftText3_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        coverLeftText3_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 封面视频展示项 3
     * </pre>
     *
     * <code>string cover_left_text_3 = 7;</code>
     * @return The bytes for coverLeftText3.
     */
    public com.google.protobuf.ByteString
        getCoverLeftText3Bytes() {
      Object ref = coverLeftText3_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        coverLeftText3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 封面视频展示项 3
     * </pre>
     *
     * <code>string cover_left_text_3 = 7;</code>
     * @param value The coverLeftText3 to set.
     * @return This builder for chaining.
     */
    public Builder setCoverLeftText3(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      coverLeftText3_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 封面视频展示项 3
     * </pre>
     *
     * <code>string cover_left_text_3 = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearCoverLeftText3() {
      
      coverLeftText3_ = getDefaultInstance().getCoverLeftText3();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 封面视频展示项 3
     * </pre>
     *
     * <code>string cover_left_text_3 = 7;</code>
     * @param value The bytes for coverLeftText3 to set.
     * @return This builder for chaining.
     */
    public Builder setCoverLeftText3Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      coverLeftText3_ = value;
      onChanged();
      return this;
    }

    private java.util.List<VideoBadge> badge_ =
      java.util.Collections.emptyList();
    private void ensureBadgeIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        badge_ = new java.util.ArrayList<VideoBadge>(badge_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        VideoBadge, VideoBadge.Builder, VideoBadgeOrBuilder> badgeBuilder_;

    /**
     * <pre>
     * 角标
     * </pre>
     *
     * <code>repeated .bilibili.app.dynamic.v1.VideoBadge badge = 8;</code>
     */
    public java.util.List<VideoBadge> getBadgeList() {
      if (badgeBuilder_ == null) {
        return java.util.Collections.unmodifiableList(badge_);
      } else {
        return badgeBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 角标
     * </pre>
     *
     * <code>repeated .bilibili.app.dynamic.v1.VideoBadge badge = 8;</code>
     */
    public int getBadgeCount() {
      if (badgeBuilder_ == null) {
        return badge_.size();
      } else {
        return badgeBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 角标
     * </pre>
     *
     * <code>repeated .bilibili.app.dynamic.v1.VideoBadge badge = 8;</code>
     */
    public VideoBadge getBadge(int index) {
      if (badgeBuilder_ == null) {
        return badge_.get(index);
      } else {
        return badgeBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 角标
     * </pre>
     *
     * <code>repeated .bilibili.app.dynamic.v1.VideoBadge badge = 8;</code>
     */
    public Builder setBadge(
        int index, VideoBadge value) {
      if (badgeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBadgeIsMutable();
        badge_.set(index, value);
        onChanged();
      } else {
        badgeBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 角标
     * </pre>
     *
     * <code>repeated .bilibili.app.dynamic.v1.VideoBadge badge = 8;</code>
     */
    public Builder setBadge(
        int index, VideoBadge.Builder builderForValue) {
      if (badgeBuilder_ == null) {
        ensureBadgeIsMutable();
        badge_.set(index, builderForValue.build());
        onChanged();
      } else {
        badgeBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 角标
     * </pre>
     *
     * <code>repeated .bilibili.app.dynamic.v1.VideoBadge badge = 8;</code>
     */
    public Builder addBadge(VideoBadge value) {
      if (badgeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBadgeIsMutable();
        badge_.add(value);
        onChanged();
      } else {
        badgeBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 角标
     * </pre>
     *
     * <code>repeated .bilibili.app.dynamic.v1.VideoBadge badge = 8;</code>
     */
    public Builder addBadge(
        int index, VideoBadge value) {
      if (badgeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBadgeIsMutable();
        badge_.add(index, value);
        onChanged();
      } else {
        badgeBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 角标
     * </pre>
     *
     * <code>repeated .bilibili.app.dynamic.v1.VideoBadge badge = 8;</code>
     */
    public Builder addBadge(
        VideoBadge.Builder builderForValue) {
      if (badgeBuilder_ == null) {
        ensureBadgeIsMutable();
        badge_.add(builderForValue.build());
        onChanged();
      } else {
        badgeBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 角标
     * </pre>
     *
     * <code>repeated .bilibili.app.dynamic.v1.VideoBadge badge = 8;</code>
     */
    public Builder addBadge(
        int index, VideoBadge.Builder builderForValue) {
      if (badgeBuilder_ == null) {
        ensureBadgeIsMutable();
        badge_.add(index, builderForValue.build());
        onChanged();
      } else {
        badgeBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 角标
     * </pre>
     *
     * <code>repeated .bilibili.app.dynamic.v1.VideoBadge badge = 8;</code>
     */
    public Builder addAllBadge(
        Iterable<? extends VideoBadge> values) {
      if (badgeBuilder_ == null) {
        ensureBadgeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, badge_);
        onChanged();
      } else {
        badgeBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 角标
     * </pre>
     *
     * <code>repeated .bilibili.app.dynamic.v1.VideoBadge badge = 8;</code>
     */
    public Builder clearBadge() {
      if (badgeBuilder_ == null) {
        badge_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        badgeBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 角标
     * </pre>
     *
     * <code>repeated .bilibili.app.dynamic.v1.VideoBadge badge = 8;</code>
     */
    public Builder removeBadge(int index) {
      if (badgeBuilder_ == null) {
        ensureBadgeIsMutable();
        badge_.remove(index);
        onChanged();
      } else {
        badgeBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 角标
     * </pre>
     *
     * <code>repeated .bilibili.app.dynamic.v1.VideoBadge badge = 8;</code>
     */
    public VideoBadge.Builder getBadgeBuilder(
        int index) {
      return getBadgeFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 角标
     * </pre>
     *
     * <code>repeated .bilibili.app.dynamic.v1.VideoBadge badge = 8;</code>
     */
    public VideoBadgeOrBuilder getBadgeOrBuilder(
        int index) {
      if (badgeBuilder_ == null) {
        return badge_.get(index);  } else {
        return badgeBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 角标
     * </pre>
     *
     * <code>repeated .bilibili.app.dynamic.v1.VideoBadge badge = 8;</code>
     */
    public java.util.List<? extends VideoBadgeOrBuilder>
         getBadgeOrBuilderList() {
      if (badgeBuilder_ != null) {
        return badgeBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(badge_);
      }
    }
    /**
     * <pre>
     * 角标
     * </pre>
     *
     * <code>repeated .bilibili.app.dynamic.v1.VideoBadge badge = 8;</code>
     */
    public VideoBadge.Builder addBadgeBuilder() {
      return getBadgeFieldBuilder().addBuilder(
          VideoBadge.getDefaultInstance());
    }
    /**
     * <pre>
     * 角标
     * </pre>
     *
     * <code>repeated .bilibili.app.dynamic.v1.VideoBadge badge = 8;</code>
     */
    public VideoBadge.Builder addBadgeBuilder(
        int index) {
      return getBadgeFieldBuilder().addBuilder(
          index, VideoBadge.getDefaultInstance());
    }
    /**
     * <pre>
     * 角标
     * </pre>
     *
     * <code>repeated .bilibili.app.dynamic.v1.VideoBadge badge = 8;</code>
     */
    public java.util.List<VideoBadge.Builder>
         getBadgeBuilderList() {
      return getBadgeFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        VideoBadge, VideoBadge.Builder, VideoBadgeOrBuilder>
        getBadgeFieldBuilder() {
      if (badgeBuilder_ == null) {
        badgeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            VideoBadge, VideoBadge.Builder, VideoBadgeOrBuilder>(
                badge_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        badge_ = null;
      }
      return badgeBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bilibili.app.dynamic.v1.DynOurCityModuleCover)
  }

  // @@protoc_insertion_point(class_scope:bilibili.app.dynamic.v1.DynOurCityModuleCover)
  private static final DynOurCityModuleCover DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new DynOurCityModuleCover();
  }

  public static DynOurCityModuleCover getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DynOurCityModuleCover>
      PARSER = new com.google.protobuf.AbstractParser<DynOurCityModuleCover>() {
    @Override
    public DynOurCityModuleCover parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DynOurCityModuleCover(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DynOurCityModuleCover> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<DynOurCityModuleCover> getParserForType() {
    return PARSER;
  }

  @Override
  public DynOurCityModuleCover getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

