// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/app/dynamic/v1/dynamic.proto

package com.bapis.bilibili.app.dynamic.v1;

/**
 * <pre>
 * DynRedReply 红点接口返回值
 * </pre>
 *
 * Protobuf type {@code bilibili.app.dynamic.v1.DynRedReply}
 */
public final class DynRedReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bilibili.app.dynamic.v1.DynRedReply)
    DynRedReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DynRedReply.newBuilder() to construct.
  private DynRedReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DynRedReply() {
    redType_ = "";
    defaultTab_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new DynRedReply();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DynRedReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            redType_ = s;
            break;
          }
          case 18: {
            DynRedItem.Builder subBuilder = null;
            if (dynRedItem_ != null) {
              subBuilder = dynRedItem_.toBuilder();
            }
            dynRedItem_ = input.readMessage(DynRedItem.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dynRedItem_);
              dynRedItem_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            defaultTab_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return DynamicOuterClass.internal_static_bilibili_app_dynamic_v1_DynRedReply_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return DynamicOuterClass.internal_static_bilibili_app_dynamic_v1_DynRedReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            DynRedReply.class, Builder.class);
  }

  public static final int RED_TYPE_FIELD_NUMBER = 1;
  private volatile Object redType_;
  /**
   * <pre>
   * 类型 count-数字红点 point-普通红点 no_point-没有红点
   * </pre>
   *
   * <code>string red_type = 1;</code>
   * @return The redType.
   */
  @Override
  public String getRedType() {
    Object ref = redType_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      redType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 类型 count-数字红点 point-普通红点 no_point-没有红点
   * </pre>
   *
   * <code>string red_type = 1;</code>
   * @return The bytes for redType.
   */
  @Override
  public com.google.protobuf.ByteString
      getRedTypeBytes() {
    Object ref = redType_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      redType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DYN_RED_ITEM_FIELD_NUMBER = 2;
  private DynRedItem dynRedItem_;
  /**
   * <pre>
   * 红点具体信息
   * </pre>
   *
   * <code>.bilibili.app.dynamic.v1.DynRedItem dyn_red_item = 2;</code>
   * @return Whether the dynRedItem field is set.
   */
  @Override
  public boolean hasDynRedItem() {
    return dynRedItem_ != null;
  }
  /**
   * <pre>
   * 红点具体信息
   * </pre>
   *
   * <code>.bilibili.app.dynamic.v1.DynRedItem dyn_red_item = 2;</code>
   * @return The dynRedItem.
   */
  @Override
  public DynRedItem getDynRedItem() {
    return dynRedItem_ == null ? DynRedItem.getDefaultInstance() : dynRedItem_;
  }
  /**
   * <pre>
   * 红点具体信息
   * </pre>
   *
   * <code>.bilibili.app.dynamic.v1.DynRedItem dyn_red_item = 2;</code>
   */
  @Override
  public DynRedItemOrBuilder getDynRedItemOrBuilder() {
    return getDynRedItem();
  }

  public static final int DEFAULT_TAB_FIELD_NUMBER = 3;
  private volatile Object defaultTab_;
  /**
   * <pre>
   * 默认tab 值对应tab接口下发的anchor
   * </pre>
   *
   * <code>string default_tab = 3;</code>
   * @return The defaultTab.
   */
  @Override
  public String getDefaultTab() {
    Object ref = defaultTab_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      defaultTab_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 默认tab 值对应tab接口下发的anchor
   * </pre>
   *
   * <code>string default_tab = 3;</code>
   * @return The bytes for defaultTab.
   */
  @Override
  public com.google.protobuf.ByteString
      getDefaultTabBytes() {
    Object ref = defaultTab_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      defaultTab_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getRedTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, redType_);
    }
    if (dynRedItem_ != null) {
      output.writeMessage(2, getDynRedItem());
    }
    if (!getDefaultTabBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, defaultTab_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getRedTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, redType_);
    }
    if (dynRedItem_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getDynRedItem());
    }
    if (!getDefaultTabBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, defaultTab_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof DynRedReply)) {
      return super.equals(obj);
    }
    DynRedReply other = (DynRedReply) obj;

    if (!getRedType()
        .equals(other.getRedType())) return false;
    if (hasDynRedItem() != other.hasDynRedItem()) return false;
    if (hasDynRedItem()) {
      if (!getDynRedItem()
          .equals(other.getDynRedItem())) return false;
    }
    if (!getDefaultTab()
        .equals(other.getDefaultTab())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RED_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getRedType().hashCode();
    if (hasDynRedItem()) {
      hash = (37 * hash) + DYN_RED_ITEM_FIELD_NUMBER;
      hash = (53 * hash) + getDynRedItem().hashCode();
    }
    hash = (37 * hash) + DEFAULT_TAB_FIELD_NUMBER;
    hash = (53 * hash) + getDefaultTab().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static DynRedReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DynRedReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DynRedReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DynRedReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DynRedReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DynRedReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DynRedReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DynRedReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static DynRedReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static DynRedReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static DynRedReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DynRedReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(DynRedReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * DynRedReply 红点接口返回值
   * </pre>
   *
   * Protobuf type {@code bilibili.app.dynamic.v1.DynRedReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bilibili.app.dynamic.v1.DynRedReply)
      DynRedReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DynamicOuterClass.internal_static_bilibili_app_dynamic_v1_DynRedReply_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DynamicOuterClass.internal_static_bilibili_app_dynamic_v1_DynRedReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DynRedReply.class, Builder.class);
    }

    // Construct using com.bapis.bilibili.app.dynamic.v1.DynRedReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      redType_ = "";

      if (dynRedItemBuilder_ == null) {
        dynRedItem_ = null;
      } else {
        dynRedItem_ = null;
        dynRedItemBuilder_ = null;
      }
      defaultTab_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return DynamicOuterClass.internal_static_bilibili_app_dynamic_v1_DynRedReply_descriptor;
    }

    @Override
    public DynRedReply getDefaultInstanceForType() {
      return DynRedReply.getDefaultInstance();
    }

    @Override
    public DynRedReply build() {
      DynRedReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public DynRedReply buildPartial() {
      DynRedReply result = new DynRedReply(this);
      result.redType_ = redType_;
      if (dynRedItemBuilder_ == null) {
        result.dynRedItem_ = dynRedItem_;
      } else {
        result.dynRedItem_ = dynRedItemBuilder_.build();
      }
      result.defaultTab_ = defaultTab_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof DynRedReply) {
        return mergeFrom((DynRedReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(DynRedReply other) {
      if (other == DynRedReply.getDefaultInstance()) return this;
      if (!other.getRedType().isEmpty()) {
        redType_ = other.redType_;
        onChanged();
      }
      if (other.hasDynRedItem()) {
        mergeDynRedItem(other.getDynRedItem());
      }
      if (!other.getDefaultTab().isEmpty()) {
        defaultTab_ = other.defaultTab_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      DynRedReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (DynRedReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object redType_ = "";
    /**
     * <pre>
     * 类型 count-数字红点 point-普通红点 no_point-没有红点
     * </pre>
     *
     * <code>string red_type = 1;</code>
     * @return The redType.
     */
    public String getRedType() {
      Object ref = redType_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        redType_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 类型 count-数字红点 point-普通红点 no_point-没有红点
     * </pre>
     *
     * <code>string red_type = 1;</code>
     * @return The bytes for redType.
     */
    public com.google.protobuf.ByteString
        getRedTypeBytes() {
      Object ref = redType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        redType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 类型 count-数字红点 point-普通红点 no_point-没有红点
     * </pre>
     *
     * <code>string red_type = 1;</code>
     * @param value The redType to set.
     * @return This builder for chaining.
     */
    public Builder setRedType(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      redType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 类型 count-数字红点 point-普通红点 no_point-没有红点
     * </pre>
     *
     * <code>string red_type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRedType() {
      
      redType_ = getDefaultInstance().getRedType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 类型 count-数字红点 point-普通红点 no_point-没有红点
     * </pre>
     *
     * <code>string red_type = 1;</code>
     * @param value The bytes for redType to set.
     * @return This builder for chaining.
     */
    public Builder setRedTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      redType_ = value;
      onChanged();
      return this;
    }

    private DynRedItem dynRedItem_;
    private com.google.protobuf.SingleFieldBuilderV3<
        DynRedItem, DynRedItem.Builder, DynRedItemOrBuilder> dynRedItemBuilder_;
    /**
     * <pre>
     * 红点具体信息
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v1.DynRedItem dyn_red_item = 2;</code>
     * @return Whether the dynRedItem field is set.
     */
    public boolean hasDynRedItem() {
      return dynRedItemBuilder_ != null || dynRedItem_ != null;
    }
    /**
     * <pre>
     * 红点具体信息
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v1.DynRedItem dyn_red_item = 2;</code>
     * @return The dynRedItem.
     */
    public DynRedItem getDynRedItem() {
      if (dynRedItemBuilder_ == null) {
        return dynRedItem_ == null ? DynRedItem.getDefaultInstance() : dynRedItem_;
      } else {
        return dynRedItemBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 红点具体信息
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v1.DynRedItem dyn_red_item = 2;</code>
     */
    public Builder setDynRedItem(DynRedItem value) {
      if (dynRedItemBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dynRedItem_ = value;
        onChanged();
      } else {
        dynRedItemBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 红点具体信息
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v1.DynRedItem dyn_red_item = 2;</code>
     */
    public Builder setDynRedItem(
        DynRedItem.Builder builderForValue) {
      if (dynRedItemBuilder_ == null) {
        dynRedItem_ = builderForValue.build();
        onChanged();
      } else {
        dynRedItemBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 红点具体信息
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v1.DynRedItem dyn_red_item = 2;</code>
     */
    public Builder mergeDynRedItem(DynRedItem value) {
      if (dynRedItemBuilder_ == null) {
        if (dynRedItem_ != null) {
          dynRedItem_ =
            DynRedItem.newBuilder(dynRedItem_).mergeFrom(value).buildPartial();
        } else {
          dynRedItem_ = value;
        }
        onChanged();
      } else {
        dynRedItemBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 红点具体信息
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v1.DynRedItem dyn_red_item = 2;</code>
     */
    public Builder clearDynRedItem() {
      if (dynRedItemBuilder_ == null) {
        dynRedItem_ = null;
        onChanged();
      } else {
        dynRedItem_ = null;
        dynRedItemBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 红点具体信息
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v1.DynRedItem dyn_red_item = 2;</code>
     */
    public DynRedItem.Builder getDynRedItemBuilder() {
      
      onChanged();
      return getDynRedItemFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 红点具体信息
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v1.DynRedItem dyn_red_item = 2;</code>
     */
    public DynRedItemOrBuilder getDynRedItemOrBuilder() {
      if (dynRedItemBuilder_ != null) {
        return dynRedItemBuilder_.getMessageOrBuilder();
      } else {
        return dynRedItem_ == null ?
            DynRedItem.getDefaultInstance() : dynRedItem_;
      }
    }
    /**
     * <pre>
     * 红点具体信息
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v1.DynRedItem dyn_red_item = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        DynRedItem, DynRedItem.Builder, DynRedItemOrBuilder>
        getDynRedItemFieldBuilder() {
      if (dynRedItemBuilder_ == null) {
        dynRedItemBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            DynRedItem, DynRedItem.Builder, DynRedItemOrBuilder>(
                getDynRedItem(),
                getParentForChildren(),
                isClean());
        dynRedItem_ = null;
      }
      return dynRedItemBuilder_;
    }

    private Object defaultTab_ = "";
    /**
     * <pre>
     * 默认tab 值对应tab接口下发的anchor
     * </pre>
     *
     * <code>string default_tab = 3;</code>
     * @return The defaultTab.
     */
    public String getDefaultTab() {
      Object ref = defaultTab_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        defaultTab_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 默认tab 值对应tab接口下发的anchor
     * </pre>
     *
     * <code>string default_tab = 3;</code>
     * @return The bytes for defaultTab.
     */
    public com.google.protobuf.ByteString
        getDefaultTabBytes() {
      Object ref = defaultTab_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        defaultTab_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 默认tab 值对应tab接口下发的anchor
     * </pre>
     *
     * <code>string default_tab = 3;</code>
     * @param value The defaultTab to set.
     * @return This builder for chaining.
     */
    public Builder setDefaultTab(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      defaultTab_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 默认tab 值对应tab接口下发的anchor
     * </pre>
     *
     * <code>string default_tab = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDefaultTab() {
      
      defaultTab_ = getDefaultInstance().getDefaultTab();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 默认tab 值对应tab接口下发的anchor
     * </pre>
     *
     * <code>string default_tab = 3;</code>
     * @param value The bytes for defaultTab to set.
     * @return This builder for chaining.
     */
    public Builder setDefaultTabBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      defaultTab_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bilibili.app.dynamic.v1.DynRedReply)
  }

  // @@protoc_insertion_point(class_scope:bilibili.app.dynamic.v1.DynRedReply)
  private static final DynRedReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new DynRedReply();
  }

  public static DynRedReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DynRedReply>
      PARSER = new com.google.protobuf.AbstractParser<DynRedReply>() {
    @Override
    public DynRedReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DynRedReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DynRedReply> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<DynRedReply> getParserForType() {
    return PARSER;
  }

  @Override
  public DynRedReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

