// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/app/dynamic/v1/dynamic.proto

package com.bapis.bilibili.app.dynamic.v1;

public interface FollowListItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bilibili.app.dynamic.v1.FollowListItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * season_id
   * </pre>
   *
   * <code>int32 season_id = 1;</code>
   * @return The seasonId.
   */
  int getSeasonId();

  /**
   * <pre>
   * 标题
   * </pre>
   *
   * <code>string title = 2;</code>
   * @return The title.
   */
  String getTitle();
  /**
   * <pre>
   * 标题
   * </pre>
   *
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <pre>
   * 封面图
   * </pre>
   *
   * <code>string cover = 3;</code>
   * @return The cover.
   */
  String getCover();
  /**
   * <pre>
   * 封面图
   * </pre>
   *
   * <code>string cover = 3;</code>
   * @return The bytes for cover.
   */
  com.google.protobuf.ByteString
      getCoverBytes();

  /**
   * <pre>
   * 跳转链接
   * </pre>
   *
   * <code>string url = 4;</code>
   * @return The url.
   */
  String getUrl();
  /**
   * <pre>
   * 跳转链接
   * </pre>
   *
   * <code>string url = 4;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <pre>
   * new_ep
   * </pre>
   *
   * <code>.bilibili.app.dynamic.v1.NewEP new_ep = 5;</code>
   * @return Whether the newEp field is set.
   */
  boolean hasNewEp();
  /**
   * <pre>
   * new_ep
   * </pre>
   *
   * <code>.bilibili.app.dynamic.v1.NewEP new_ep = 5;</code>
   * @return The newEp.
   */
  NewEP getNewEp();
  /**
   * <pre>
   * new_ep
   * </pre>
   *
   * <code>.bilibili.app.dynamic.v1.NewEP new_ep = 5;</code>
   */
  NewEPOrBuilder getNewEpOrBuilder();
}
