// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/app/dynamic/v1/dynamic.proto

package com.bapis.bilibili.app.dynamic.v1;

public interface LikeAnimationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bilibili.app.dynamic.v1.LikeAnimation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 开始动画
   * </pre>
   *
   * <code>string begin = 1;</code>
   * @return The begin.
   */
  String getBegin();
  /**
   * <pre>
   * 开始动画
   * </pre>
   *
   * <code>string begin = 1;</code>
   * @return The bytes for begin.
   */
  com.google.protobuf.ByteString
      getBeginBytes();

  /**
   * <pre>
   * 过程动画
   * </pre>
   *
   * <code>string proc = 2;</code>
   * @return The proc.
   */
  String getProc();
  /**
   * <pre>
   * 过程动画
   * </pre>
   *
   * <code>string proc = 2;</code>
   * @return The bytes for proc.
   */
  com.google.protobuf.ByteString
      getProcBytes();

  /**
   * <pre>
   * 结束动画
   * </pre>
   *
   * <code>string end = 3;</code>
   * @return The end.
   */
  String getEnd();
  /**
   * <pre>
   * 结束动画
   * </pre>
   *
   * <code>string end = 3;</code>
   * @return The bytes for end.
   */
  com.google.protobuf.ByteString
      getEndBytes();

  /**
   * <pre>
   * id
   * </pre>
   *
   * <code>int64 like_icon_id = 4;</code>
   * @return The likeIconId.
   */
  long getLikeIconId();
}
