// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/app/dynamic/v1/dynamic.proto

package com.bapis.bilibili.app.dynamic.v1;

/**
 * <pre>
 * StatInfo 计数内容
 * </pre>
 *
 * Protobuf type {@code bilibili.app.dynamic.v1.SVideoStatInfo}
 */
public final class SVideoStatInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bilibili.app.dynamic.v1.SVideoStatInfo)
    SVideoStatInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SVideoStatInfo.newBuilder() to construct.
  private SVideoStatInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SVideoStatInfo() {
    uri_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new SVideoStatInfo();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SVideoStatInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            icon_ = input.readInt32();
            break;
          }
          case 16: {

            num_ = input.readInt64();
            break;
          }
          case 24: {

            selected_ = input.readInt32();
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            uri_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return DynamicOuterClass.internal_static_bilibili_app_dynamic_v1_SVideoStatInfo_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return DynamicOuterClass.internal_static_bilibili_app_dynamic_v1_SVideoStatInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            SVideoStatInfo.class, Builder.class);
  }

  public static final int ICON_FIELD_NUMBER = 1;
  private int icon_;
  /**
   * <pre>
   * 计数icon 1-分享符号 2-评论符号 3-点赞符号
   * </pre>
   *
   * <code>int32 icon = 1;</code>
   * @return The icon.
   */
  @Override
  public int getIcon() {
    return icon_;
  }

  public static final int NUM_FIELD_NUMBER = 2;
  private long num_;
  /**
   * <pre>
   * 计数值
   * </pre>
   *
   * <code>int64 num = 2;</code>
   * @return The num.
   */
  @Override
  public long getNum() {
    return num_;
  }

  public static final int SELECTED_FIELD_NUMBER = 3;
  private int selected_;
  /**
   * <pre>
   * 选中状态 1-选中
   * </pre>
   *
   * <code>int32 selected = 3;</code>
   * @return The selected.
   */
  @Override
  public int getSelected() {
    return selected_;
  }

  public static final int URI_FIELD_NUMBER = 4;
  private volatile Object uri_;
  /**
   * <pre>
   * 跳转链接（如评论）
   * </pre>
   *
   * <code>string uri = 4;</code>
   * @return The uri.
   */
  @Override
  public String getUri() {
    Object ref = uri_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      uri_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 跳转链接（如评论）
   * </pre>
   *
   * <code>string uri = 4;</code>
   * @return The bytes for uri.
   */
  @Override
  public com.google.protobuf.ByteString
      getUriBytes() {
    Object ref = uri_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      uri_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (icon_ != 0) {
      output.writeInt32(1, icon_);
    }
    if (num_ != 0L) {
      output.writeInt64(2, num_);
    }
    if (selected_ != 0) {
      output.writeInt32(3, selected_);
    }
    if (!getUriBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, uri_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (icon_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, icon_);
    }
    if (num_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, num_);
    }
    if (selected_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, selected_);
    }
    if (!getUriBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, uri_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof SVideoStatInfo)) {
      return super.equals(obj);
    }
    SVideoStatInfo other = (SVideoStatInfo) obj;

    if (getIcon()
        != other.getIcon()) return false;
    if (getNum()
        != other.getNum()) return false;
    if (getSelected()
        != other.getSelected()) return false;
    if (!getUri()
        .equals(other.getUri())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ICON_FIELD_NUMBER;
    hash = (53 * hash) + getIcon();
    hash = (37 * hash) + NUM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getNum());
    hash = (37 * hash) + SELECTED_FIELD_NUMBER;
    hash = (53 * hash) + getSelected();
    hash = (37 * hash) + URI_FIELD_NUMBER;
    hash = (53 * hash) + getUri().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static SVideoStatInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SVideoStatInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SVideoStatInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SVideoStatInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SVideoStatInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SVideoStatInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SVideoStatInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SVideoStatInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static SVideoStatInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static SVideoStatInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static SVideoStatInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SVideoStatInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(SVideoStatInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * StatInfo 计数内容
   * </pre>
   *
   * Protobuf type {@code bilibili.app.dynamic.v1.SVideoStatInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bilibili.app.dynamic.v1.SVideoStatInfo)
      SVideoStatInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DynamicOuterClass.internal_static_bilibili_app_dynamic_v1_SVideoStatInfo_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DynamicOuterClass.internal_static_bilibili_app_dynamic_v1_SVideoStatInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SVideoStatInfo.class, Builder.class);
    }

    // Construct using com.bapis.bilibili.app.dynamic.v1.SVideoStatInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      icon_ = 0;

      num_ = 0L;

      selected_ = 0;

      uri_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return DynamicOuterClass.internal_static_bilibili_app_dynamic_v1_SVideoStatInfo_descriptor;
    }

    @Override
    public SVideoStatInfo getDefaultInstanceForType() {
      return SVideoStatInfo.getDefaultInstance();
    }

    @Override
    public SVideoStatInfo build() {
      SVideoStatInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public SVideoStatInfo buildPartial() {
      SVideoStatInfo result = new SVideoStatInfo(this);
      result.icon_ = icon_;
      result.num_ = num_;
      result.selected_ = selected_;
      result.uri_ = uri_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof SVideoStatInfo) {
        return mergeFrom((SVideoStatInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(SVideoStatInfo other) {
      if (other == SVideoStatInfo.getDefaultInstance()) return this;
      if (other.getIcon() != 0) {
        setIcon(other.getIcon());
      }
      if (other.getNum() != 0L) {
        setNum(other.getNum());
      }
      if (other.getSelected() != 0) {
        setSelected(other.getSelected());
      }
      if (!other.getUri().isEmpty()) {
        uri_ = other.uri_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      SVideoStatInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (SVideoStatInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int icon_ ;
    /**
     * <pre>
     * 计数icon 1-分享符号 2-评论符号 3-点赞符号
     * </pre>
     *
     * <code>int32 icon = 1;</code>
     * @return The icon.
     */
    @Override
    public int getIcon() {
      return icon_;
    }
    /**
     * <pre>
     * 计数icon 1-分享符号 2-评论符号 3-点赞符号
     * </pre>
     *
     * <code>int32 icon = 1;</code>
     * @param value The icon to set.
     * @return This builder for chaining.
     */
    public Builder setIcon(int value) {
      
      icon_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 计数icon 1-分享符号 2-评论符号 3-点赞符号
     * </pre>
     *
     * <code>int32 icon = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIcon() {
      
      icon_ = 0;
      onChanged();
      return this;
    }

    private long num_ ;
    /**
     * <pre>
     * 计数值
     * </pre>
     *
     * <code>int64 num = 2;</code>
     * @return The num.
     */
    @Override
    public long getNum() {
      return num_;
    }
    /**
     * <pre>
     * 计数值
     * </pre>
     *
     * <code>int64 num = 2;</code>
     * @param value The num to set.
     * @return This builder for chaining.
     */
    public Builder setNum(long value) {
      
      num_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 计数值
     * </pre>
     *
     * <code>int64 num = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNum() {
      
      num_ = 0L;
      onChanged();
      return this;
    }

    private int selected_ ;
    /**
     * <pre>
     * 选中状态 1-选中
     * </pre>
     *
     * <code>int32 selected = 3;</code>
     * @return The selected.
     */
    @Override
    public int getSelected() {
      return selected_;
    }
    /**
     * <pre>
     * 选中状态 1-选中
     * </pre>
     *
     * <code>int32 selected = 3;</code>
     * @param value The selected to set.
     * @return This builder for chaining.
     */
    public Builder setSelected(int value) {
      
      selected_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 选中状态 1-选中
     * </pre>
     *
     * <code>int32 selected = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSelected() {
      
      selected_ = 0;
      onChanged();
      return this;
    }

    private Object uri_ = "";
    /**
     * <pre>
     * 跳转链接（如评论）
     * </pre>
     *
     * <code>string uri = 4;</code>
     * @return The uri.
     */
    public String getUri() {
      Object ref = uri_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        uri_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 跳转链接（如评论）
     * </pre>
     *
     * <code>string uri = 4;</code>
     * @return The bytes for uri.
     */
    public com.google.protobuf.ByteString
        getUriBytes() {
      Object ref = uri_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        uri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 跳转链接（如评论）
     * </pre>
     *
     * <code>string uri = 4;</code>
     * @param value The uri to set.
     * @return This builder for chaining.
     */
    public Builder setUri(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      uri_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 跳转链接（如评论）
     * </pre>
     *
     * <code>string uri = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUri() {
      
      uri_ = getDefaultInstance().getUri();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 跳转链接（如评论）
     * </pre>
     *
     * <code>string uri = 4;</code>
     * @param value The bytes for uri to set.
     * @return This builder for chaining.
     */
    public Builder setUriBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      uri_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bilibili.app.dynamic.v1.SVideoStatInfo)
  }

  // @@protoc_insertion_point(class_scope:bilibili.app.dynamic.v1.SVideoStatInfo)
  private static final SVideoStatInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new SVideoStatInfo();
  }

  public static SVideoStatInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SVideoStatInfo>
      PARSER = new com.google.protobuf.AbstractParser<SVideoStatInfo>() {
    @Override
    public SVideoStatInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SVideoStatInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SVideoStatInfo> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<SVideoStatInfo> getParserForType() {
    return PARSER;
  }

  @Override
  public SVideoStatInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

