// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/app/dynamic/v2/dynamic.proto

package com.bapis.bilibili.app.dynamic.v2;

/**
 * Protobuf enum {@code bilibili.app.dynamic.v2.AddButtonType}
 */
public enum AddButtonType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   *占位
   * </pre>
   *
   * <code>bt_none = 0;</code>
   */
  bt_none(0),
  /**
   * <pre>
   * 跳转
   * </pre>
   *
   * <code>bt_jump = 1;</code>
   */
  bt_jump(1),
  /**
   * <pre>
   * 按钮
   * </pre>
   *
   * <code>bt_button = 2;</code>
   */
  bt_button(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   *占位
   * </pre>
   *
   * <code>bt_none = 0;</code>
   */
  public static final int bt_none_VALUE = 0;
  /**
   * <pre>
   * 跳转
   * </pre>
   *
   * <code>bt_jump = 1;</code>
   */
  public static final int bt_jump_VALUE = 1;
  /**
   * <pre>
   * 按钮
   * </pre>
   *
   * <code>bt_button = 2;</code>
   */
  public static final int bt_button_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static AddButtonType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static AddButtonType forNumber(int value) {
    switch (value) {
      case 0: return bt_none;
      case 1: return bt_jump;
      case 2: return bt_button;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<AddButtonType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      AddButtonType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<AddButtonType>() {
          public AddButtonType findValueByNumber(int number) {
            return AddButtonType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.bapis.bilibili.app.dynamic.v2.DynamicOuterClass.getDescriptor().getEnumTypes().get(15);
  }

  private static final AddButtonType[] VALUES = values();

  public static AddButtonType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private AddButtonType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:bilibili.app.dynamic.v2.AddButtonType)
}

