// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/app/dynamic/v2/dynamic.proto

package com.bapis.bilibili.app.dynamic.v2;

/**
 * <pre>
 * AdditionalButton 动态-附加卡-按钮
 * </pre>
 *
 * Protobuf type {@code bilibili.app.dynamic.v2.AdditionalButton}
 */
public final class AdditionalButton extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bilibili.app.dynamic.v2.AdditionalButton)
    AdditionalButtonOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AdditionalButton.newBuilder() to construct.
  private AdditionalButton(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AdditionalButton() {
    type_ = 0;
    jumpUrl_ = "";
    status_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AdditionalButton();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AdditionalButton(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 18: {
            com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle.Builder subBuilder = null;
            if (jumpStyle_ != null) {
              subBuilder = jumpStyle_.toBuilder();
            }
            jumpStyle_ = input.readMessage(com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(jumpStyle_);
              jumpStyle_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            jumpUrl_ = s;
            break;
          }
          case 34: {
            com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle.Builder subBuilder = null;
            if (uncheck_ != null) {
              subBuilder = uncheck_.toBuilder();
            }
            uncheck_ = input.readMessage(com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(uncheck_);
              uncheck_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle.Builder subBuilder = null;
            if (check_ != null) {
              subBuilder = check_.toBuilder();
            }
            check_ = input.readMessage(com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(check_);
              check_ = subBuilder.buildPartial();
            }

            break;
          }
          case 48: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bapis.bilibili.app.dynamic.v2.DynamicOuterClass.internal_static_bilibili_app_dynamic_v2_AdditionalButton_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bapis.bilibili.app.dynamic.v2.DynamicOuterClass.internal_static_bilibili_app_dynamic_v2_AdditionalButton_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bapis.bilibili.app.dynamic.v2.AdditionalButton.class, com.bapis.bilibili.app.dynamic.v2.AdditionalButton.Builder.class);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <pre>
   * 按钮类型
   * </pre>
   *
   * <code>.bilibili.app.dynamic.v2.AddButtonType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <pre>
   * 按钮类型
   * </pre>
   *
   * <code>.bilibili.app.dynamic.v2.AddButtonType type = 1;</code>
   * @return The type.
   */
  @java.lang.Override public com.bapis.bilibili.app.dynamic.v2.AddButtonType getType() {
    @SuppressWarnings("deprecation")
    com.bapis.bilibili.app.dynamic.v2.AddButtonType result = com.bapis.bilibili.app.dynamic.v2.AddButtonType.valueOf(type_);
    return result == null ? com.bapis.bilibili.app.dynamic.v2.AddButtonType.UNRECOGNIZED : result;
  }

  public static final int JUMP_STYLE_FIELD_NUMBER = 2;
  private com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle jumpStyle_;
  /**
   * <pre>
   * jump-跳转样式
   * </pre>
   *
   * <code>.bilibili.app.dynamic.v2.AdditionalButtonStyle jump_style = 2;</code>
   * @return Whether the jumpStyle field is set.
   */
  @java.lang.Override
  public boolean hasJumpStyle() {
    return jumpStyle_ != null;
  }
  /**
   * <pre>
   * jump-跳转样式
   * </pre>
   *
   * <code>.bilibili.app.dynamic.v2.AdditionalButtonStyle jump_style = 2;</code>
   * @return The jumpStyle.
   */
  @java.lang.Override
  public com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle getJumpStyle() {
    return jumpStyle_ == null ? com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle.getDefaultInstance() : jumpStyle_;
  }
  /**
   * <pre>
   * jump-跳转样式
   * </pre>
   *
   * <code>.bilibili.app.dynamic.v2.AdditionalButtonStyle jump_style = 2;</code>
   */
  @java.lang.Override
  public com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyleOrBuilder getJumpStyleOrBuilder() {
    return getJumpStyle();
  }

  public static final int JUMP_URL_FIELD_NUMBER = 3;
  private volatile java.lang.Object jumpUrl_;
  /**
   * <pre>
   * jump-跳转链接
   * </pre>
   *
   * <code>string jump_url = 3;</code>
   * @return The jumpUrl.
   */
  @java.lang.Override
  public java.lang.String getJumpUrl() {
    java.lang.Object ref = jumpUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      jumpUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * jump-跳转链接
   * </pre>
   *
   * <code>string jump_url = 3;</code>
   * @return The bytes for jumpUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJumpUrlBytes() {
    java.lang.Object ref = jumpUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      jumpUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UNCHECK_FIELD_NUMBER = 4;
  private com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle uncheck_;
  /**
   * <pre>
   * button-未点样式
   * </pre>
   *
   * <code>.bilibili.app.dynamic.v2.AdditionalButtonStyle uncheck = 4;</code>
   * @return Whether the uncheck field is set.
   */
  @java.lang.Override
  public boolean hasUncheck() {
    return uncheck_ != null;
  }
  /**
   * <pre>
   * button-未点样式
   * </pre>
   *
   * <code>.bilibili.app.dynamic.v2.AdditionalButtonStyle uncheck = 4;</code>
   * @return The uncheck.
   */
  @java.lang.Override
  public com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle getUncheck() {
    return uncheck_ == null ? com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle.getDefaultInstance() : uncheck_;
  }
  /**
   * <pre>
   * button-未点样式
   * </pre>
   *
   * <code>.bilibili.app.dynamic.v2.AdditionalButtonStyle uncheck = 4;</code>
   */
  @java.lang.Override
  public com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyleOrBuilder getUncheckOrBuilder() {
    return getUncheck();
  }

  public static final int CHECK_FIELD_NUMBER = 5;
  private com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle check_;
  /**
   * <pre>
   * button-已点样式
   * </pre>
   *
   * <code>.bilibili.app.dynamic.v2.AdditionalButtonStyle check = 5;</code>
   * @return Whether the check field is set.
   */
  @java.lang.Override
  public boolean hasCheck() {
    return check_ != null;
  }
  /**
   * <pre>
   * button-已点样式
   * </pre>
   *
   * <code>.bilibili.app.dynamic.v2.AdditionalButtonStyle check = 5;</code>
   * @return The check.
   */
  @java.lang.Override
  public com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle getCheck() {
    return check_ == null ? com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle.getDefaultInstance() : check_;
  }
  /**
   * <pre>
   * button-已点样式
   * </pre>
   *
   * <code>.bilibili.app.dynamic.v2.AdditionalButtonStyle check = 5;</code>
   */
  @java.lang.Override
  public com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyleOrBuilder getCheckOrBuilder() {
    return getCheck();
  }

  public static final int STATUS_FIELD_NUMBER = 6;
  private int status_;
  /**
   * <pre>
   * button-当前状态
   * </pre>
   *
   * <code>.bilibili.app.dynamic.v2.AdditionalButtonStatus status = 6;</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <pre>
   * button-当前状态
   * </pre>
   *
   * <code>.bilibili.app.dynamic.v2.AdditionalButtonStatus status = 6;</code>
   * @return The status.
   */
  @java.lang.Override public com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStatus getStatus() {
    @SuppressWarnings("deprecation")
    com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStatus result = com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStatus.valueOf(status_);
    return result == null ? com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStatus.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != com.bapis.bilibili.app.dynamic.v2.AddButtonType.bt_none.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (jumpStyle_ != null) {
      output.writeMessage(2, getJumpStyle());
    }
    if (!getJumpUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, jumpUrl_);
    }
    if (uncheck_ != null) {
      output.writeMessage(4, getUncheck());
    }
    if (check_ != null) {
      output.writeMessage(5, getCheck());
    }
    if (status_ != com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStatus.uncheck.getNumber()) {
      output.writeEnum(6, status_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != com.bapis.bilibili.app.dynamic.v2.AddButtonType.bt_none.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (jumpStyle_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getJumpStyle());
    }
    if (!getJumpUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, jumpUrl_);
    }
    if (uncheck_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getUncheck());
    }
    if (check_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getCheck());
    }
    if (status_ != com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStatus.uncheck.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, status_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bapis.bilibili.app.dynamic.v2.AdditionalButton)) {
      return super.equals(obj);
    }
    com.bapis.bilibili.app.dynamic.v2.AdditionalButton other = (com.bapis.bilibili.app.dynamic.v2.AdditionalButton) obj;

    if (type_ != other.type_) return false;
    if (hasJumpStyle() != other.hasJumpStyle()) return false;
    if (hasJumpStyle()) {
      if (!getJumpStyle()
          .equals(other.getJumpStyle())) return false;
    }
    if (!getJumpUrl()
        .equals(other.getJumpUrl())) return false;
    if (hasUncheck() != other.hasUncheck()) return false;
    if (hasUncheck()) {
      if (!getUncheck()
          .equals(other.getUncheck())) return false;
    }
    if (hasCheck() != other.hasCheck()) return false;
    if (hasCheck()) {
      if (!getCheck()
          .equals(other.getCheck())) return false;
    }
    if (status_ != other.status_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    if (hasJumpStyle()) {
      hash = (37 * hash) + JUMP_STYLE_FIELD_NUMBER;
      hash = (53 * hash) + getJumpStyle().hashCode();
    }
    hash = (37 * hash) + JUMP_URL_FIELD_NUMBER;
    hash = (53 * hash) + getJumpUrl().hashCode();
    if (hasUncheck()) {
      hash = (37 * hash) + UNCHECK_FIELD_NUMBER;
      hash = (53 * hash) + getUncheck().hashCode();
    }
    if (hasCheck()) {
      hash = (37 * hash) + CHECK_FIELD_NUMBER;
      hash = (53 * hash) + getCheck().hashCode();
    }
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bapis.bilibili.app.dynamic.v2.AdditionalButton parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bapis.bilibili.app.dynamic.v2.AdditionalButton parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bapis.bilibili.app.dynamic.v2.AdditionalButton parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bapis.bilibili.app.dynamic.v2.AdditionalButton parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bapis.bilibili.app.dynamic.v2.AdditionalButton parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bapis.bilibili.app.dynamic.v2.AdditionalButton parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bapis.bilibili.app.dynamic.v2.AdditionalButton parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bapis.bilibili.app.dynamic.v2.AdditionalButton parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bapis.bilibili.app.dynamic.v2.AdditionalButton parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bapis.bilibili.app.dynamic.v2.AdditionalButton parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bapis.bilibili.app.dynamic.v2.AdditionalButton parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bapis.bilibili.app.dynamic.v2.AdditionalButton parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bapis.bilibili.app.dynamic.v2.AdditionalButton prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * AdditionalButton 动态-附加卡-按钮
   * </pre>
   *
   * Protobuf type {@code bilibili.app.dynamic.v2.AdditionalButton}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bilibili.app.dynamic.v2.AdditionalButton)
      com.bapis.bilibili.app.dynamic.v2.AdditionalButtonOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bapis.bilibili.app.dynamic.v2.DynamicOuterClass.internal_static_bilibili_app_dynamic_v2_AdditionalButton_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bapis.bilibili.app.dynamic.v2.DynamicOuterClass.internal_static_bilibili_app_dynamic_v2_AdditionalButton_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bapis.bilibili.app.dynamic.v2.AdditionalButton.class, com.bapis.bilibili.app.dynamic.v2.AdditionalButton.Builder.class);
    }

    // Construct using com.bapis.bilibili.app.dynamic.v2.AdditionalButton.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      type_ = 0;

      if (jumpStyleBuilder_ == null) {
        jumpStyle_ = null;
      } else {
        jumpStyle_ = null;
        jumpStyleBuilder_ = null;
      }
      jumpUrl_ = "";

      if (uncheckBuilder_ == null) {
        uncheck_ = null;
      } else {
        uncheck_ = null;
        uncheckBuilder_ = null;
      }
      if (checkBuilder_ == null) {
        check_ = null;
      } else {
        check_ = null;
        checkBuilder_ = null;
      }
      status_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bapis.bilibili.app.dynamic.v2.DynamicOuterClass.internal_static_bilibili_app_dynamic_v2_AdditionalButton_descriptor;
    }

    @java.lang.Override
    public com.bapis.bilibili.app.dynamic.v2.AdditionalButton getDefaultInstanceForType() {
      return com.bapis.bilibili.app.dynamic.v2.AdditionalButton.getDefaultInstance();
    }

    @java.lang.Override
    public com.bapis.bilibili.app.dynamic.v2.AdditionalButton build() {
      com.bapis.bilibili.app.dynamic.v2.AdditionalButton result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bapis.bilibili.app.dynamic.v2.AdditionalButton buildPartial() {
      com.bapis.bilibili.app.dynamic.v2.AdditionalButton result = new com.bapis.bilibili.app.dynamic.v2.AdditionalButton(this);
      result.type_ = type_;
      if (jumpStyleBuilder_ == null) {
        result.jumpStyle_ = jumpStyle_;
      } else {
        result.jumpStyle_ = jumpStyleBuilder_.build();
      }
      result.jumpUrl_ = jumpUrl_;
      if (uncheckBuilder_ == null) {
        result.uncheck_ = uncheck_;
      } else {
        result.uncheck_ = uncheckBuilder_.build();
      }
      if (checkBuilder_ == null) {
        result.check_ = check_;
      } else {
        result.check_ = checkBuilder_.build();
      }
      result.status_ = status_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bapis.bilibili.app.dynamic.v2.AdditionalButton) {
        return mergeFrom((com.bapis.bilibili.app.dynamic.v2.AdditionalButton)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bapis.bilibili.app.dynamic.v2.AdditionalButton other) {
      if (other == com.bapis.bilibili.app.dynamic.v2.AdditionalButton.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.hasJumpStyle()) {
        mergeJumpStyle(other.getJumpStyle());
      }
      if (!other.getJumpUrl().isEmpty()) {
        jumpUrl_ = other.jumpUrl_;
        onChanged();
      }
      if (other.hasUncheck()) {
        mergeUncheck(other.getUncheck());
      }
      if (other.hasCheck()) {
        mergeCheck(other.getCheck());
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bapis.bilibili.app.dynamic.v2.AdditionalButton parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bapis.bilibili.app.dynamic.v2.AdditionalButton) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int type_ = 0;
    /**
     * <pre>
     * 按钮类型
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AddButtonType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * 按钮类型
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AddButtonType type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 按钮类型
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AddButtonType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public com.bapis.bilibili.app.dynamic.v2.AddButtonType getType() {
      @SuppressWarnings("deprecation")
      com.bapis.bilibili.app.dynamic.v2.AddButtonType result = com.bapis.bilibili.app.dynamic.v2.AddButtonType.valueOf(type_);
      return result == null ? com.bapis.bilibili.app.dynamic.v2.AddButtonType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 按钮类型
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AddButtonType type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(com.bapis.bilibili.app.dynamic.v2.AddButtonType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 按钮类型
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AddButtonType type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle jumpStyle_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle, com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle.Builder, com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyleOrBuilder> jumpStyleBuilder_;
    /**
     * <pre>
     * jump-跳转样式
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AdditionalButtonStyle jump_style = 2;</code>
     * @return Whether the jumpStyle field is set.
     */
    public boolean hasJumpStyle() {
      return jumpStyleBuilder_ != null || jumpStyle_ != null;
    }
    /**
     * <pre>
     * jump-跳转样式
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AdditionalButtonStyle jump_style = 2;</code>
     * @return The jumpStyle.
     */
    public com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle getJumpStyle() {
      if (jumpStyleBuilder_ == null) {
        return jumpStyle_ == null ? com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle.getDefaultInstance() : jumpStyle_;
      } else {
        return jumpStyleBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * jump-跳转样式
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AdditionalButtonStyle jump_style = 2;</code>
     */
    public Builder setJumpStyle(com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle value) {
      if (jumpStyleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        jumpStyle_ = value;
        onChanged();
      } else {
        jumpStyleBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * jump-跳转样式
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AdditionalButtonStyle jump_style = 2;</code>
     */
    public Builder setJumpStyle(
        com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle.Builder builderForValue) {
      if (jumpStyleBuilder_ == null) {
        jumpStyle_ = builderForValue.build();
        onChanged();
      } else {
        jumpStyleBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * jump-跳转样式
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AdditionalButtonStyle jump_style = 2;</code>
     */
    public Builder mergeJumpStyle(com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle value) {
      if (jumpStyleBuilder_ == null) {
        if (jumpStyle_ != null) {
          jumpStyle_ =
            com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle.newBuilder(jumpStyle_).mergeFrom(value).buildPartial();
        } else {
          jumpStyle_ = value;
        }
        onChanged();
      } else {
        jumpStyleBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * jump-跳转样式
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AdditionalButtonStyle jump_style = 2;</code>
     */
    public Builder clearJumpStyle() {
      if (jumpStyleBuilder_ == null) {
        jumpStyle_ = null;
        onChanged();
      } else {
        jumpStyle_ = null;
        jumpStyleBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * jump-跳转样式
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AdditionalButtonStyle jump_style = 2;</code>
     */
    public com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle.Builder getJumpStyleBuilder() {
      
      onChanged();
      return getJumpStyleFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * jump-跳转样式
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AdditionalButtonStyle jump_style = 2;</code>
     */
    public com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyleOrBuilder getJumpStyleOrBuilder() {
      if (jumpStyleBuilder_ != null) {
        return jumpStyleBuilder_.getMessageOrBuilder();
      } else {
        return jumpStyle_ == null ?
            com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle.getDefaultInstance() : jumpStyle_;
      }
    }
    /**
     * <pre>
     * jump-跳转样式
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AdditionalButtonStyle jump_style = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle, com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle.Builder, com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyleOrBuilder> 
        getJumpStyleFieldBuilder() {
      if (jumpStyleBuilder_ == null) {
        jumpStyleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle, com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle.Builder, com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyleOrBuilder>(
                getJumpStyle(),
                getParentForChildren(),
                isClean());
        jumpStyle_ = null;
      }
      return jumpStyleBuilder_;
    }

    private java.lang.Object jumpUrl_ = "";
    /**
     * <pre>
     * jump-跳转链接
     * </pre>
     *
     * <code>string jump_url = 3;</code>
     * @return The jumpUrl.
     */
    public java.lang.String getJumpUrl() {
      java.lang.Object ref = jumpUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jumpUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * jump-跳转链接
     * </pre>
     *
     * <code>string jump_url = 3;</code>
     * @return The bytes for jumpUrl.
     */
    public com.google.protobuf.ByteString
        getJumpUrlBytes() {
      java.lang.Object ref = jumpUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jumpUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * jump-跳转链接
     * </pre>
     *
     * <code>string jump_url = 3;</code>
     * @param value The jumpUrl to set.
     * @return This builder for chaining.
     */
    public Builder setJumpUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      jumpUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * jump-跳转链接
     * </pre>
     *
     * <code>string jump_url = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearJumpUrl() {
      
      jumpUrl_ = getDefaultInstance().getJumpUrl();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * jump-跳转链接
     * </pre>
     *
     * <code>string jump_url = 3;</code>
     * @param value The bytes for jumpUrl to set.
     * @return This builder for chaining.
     */
    public Builder setJumpUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      jumpUrl_ = value;
      onChanged();
      return this;
    }

    private com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle uncheck_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle, com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle.Builder, com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyleOrBuilder> uncheckBuilder_;
    /**
     * <pre>
     * button-未点样式
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AdditionalButtonStyle uncheck = 4;</code>
     * @return Whether the uncheck field is set.
     */
    public boolean hasUncheck() {
      return uncheckBuilder_ != null || uncheck_ != null;
    }
    /**
     * <pre>
     * button-未点样式
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AdditionalButtonStyle uncheck = 4;</code>
     * @return The uncheck.
     */
    public com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle getUncheck() {
      if (uncheckBuilder_ == null) {
        return uncheck_ == null ? com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle.getDefaultInstance() : uncheck_;
      } else {
        return uncheckBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * button-未点样式
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AdditionalButtonStyle uncheck = 4;</code>
     */
    public Builder setUncheck(com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle value) {
      if (uncheckBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        uncheck_ = value;
        onChanged();
      } else {
        uncheckBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * button-未点样式
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AdditionalButtonStyle uncheck = 4;</code>
     */
    public Builder setUncheck(
        com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle.Builder builderForValue) {
      if (uncheckBuilder_ == null) {
        uncheck_ = builderForValue.build();
        onChanged();
      } else {
        uncheckBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * button-未点样式
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AdditionalButtonStyle uncheck = 4;</code>
     */
    public Builder mergeUncheck(com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle value) {
      if (uncheckBuilder_ == null) {
        if (uncheck_ != null) {
          uncheck_ =
            com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle.newBuilder(uncheck_).mergeFrom(value).buildPartial();
        } else {
          uncheck_ = value;
        }
        onChanged();
      } else {
        uncheckBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * button-未点样式
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AdditionalButtonStyle uncheck = 4;</code>
     */
    public Builder clearUncheck() {
      if (uncheckBuilder_ == null) {
        uncheck_ = null;
        onChanged();
      } else {
        uncheck_ = null;
        uncheckBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * button-未点样式
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AdditionalButtonStyle uncheck = 4;</code>
     */
    public com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle.Builder getUncheckBuilder() {
      
      onChanged();
      return getUncheckFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * button-未点样式
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AdditionalButtonStyle uncheck = 4;</code>
     */
    public com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyleOrBuilder getUncheckOrBuilder() {
      if (uncheckBuilder_ != null) {
        return uncheckBuilder_.getMessageOrBuilder();
      } else {
        return uncheck_ == null ?
            com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle.getDefaultInstance() : uncheck_;
      }
    }
    /**
     * <pre>
     * button-未点样式
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AdditionalButtonStyle uncheck = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle, com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle.Builder, com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyleOrBuilder> 
        getUncheckFieldBuilder() {
      if (uncheckBuilder_ == null) {
        uncheckBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle, com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle.Builder, com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyleOrBuilder>(
                getUncheck(),
                getParentForChildren(),
                isClean());
        uncheck_ = null;
      }
      return uncheckBuilder_;
    }

    private com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle check_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle, com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle.Builder, com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyleOrBuilder> checkBuilder_;
    /**
     * <pre>
     * button-已点样式
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AdditionalButtonStyle check = 5;</code>
     * @return Whether the check field is set.
     */
    public boolean hasCheck() {
      return checkBuilder_ != null || check_ != null;
    }
    /**
     * <pre>
     * button-已点样式
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AdditionalButtonStyle check = 5;</code>
     * @return The check.
     */
    public com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle getCheck() {
      if (checkBuilder_ == null) {
        return check_ == null ? com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle.getDefaultInstance() : check_;
      } else {
        return checkBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * button-已点样式
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AdditionalButtonStyle check = 5;</code>
     */
    public Builder setCheck(com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle value) {
      if (checkBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        check_ = value;
        onChanged();
      } else {
        checkBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * button-已点样式
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AdditionalButtonStyle check = 5;</code>
     */
    public Builder setCheck(
        com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle.Builder builderForValue) {
      if (checkBuilder_ == null) {
        check_ = builderForValue.build();
        onChanged();
      } else {
        checkBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * button-已点样式
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AdditionalButtonStyle check = 5;</code>
     */
    public Builder mergeCheck(com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle value) {
      if (checkBuilder_ == null) {
        if (check_ != null) {
          check_ =
            com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle.newBuilder(check_).mergeFrom(value).buildPartial();
        } else {
          check_ = value;
        }
        onChanged();
      } else {
        checkBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * button-已点样式
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AdditionalButtonStyle check = 5;</code>
     */
    public Builder clearCheck() {
      if (checkBuilder_ == null) {
        check_ = null;
        onChanged();
      } else {
        check_ = null;
        checkBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * button-已点样式
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AdditionalButtonStyle check = 5;</code>
     */
    public com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle.Builder getCheckBuilder() {
      
      onChanged();
      return getCheckFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * button-已点样式
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AdditionalButtonStyle check = 5;</code>
     */
    public com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyleOrBuilder getCheckOrBuilder() {
      if (checkBuilder_ != null) {
        return checkBuilder_.getMessageOrBuilder();
      } else {
        return check_ == null ?
            com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle.getDefaultInstance() : check_;
      }
    }
    /**
     * <pre>
     * button-已点样式
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AdditionalButtonStyle check = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle, com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle.Builder, com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyleOrBuilder> 
        getCheckFieldBuilder() {
      if (checkBuilder_ == null) {
        checkBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle, com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyle.Builder, com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStyleOrBuilder>(
                getCheck(),
                getParentForChildren(),
                isClean());
        check_ = null;
      }
      return checkBuilder_;
    }

    private int status_ = 0;
    /**
     * <pre>
     * button-当前状态
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AdditionalButtonStatus status = 6;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <pre>
     * button-当前状态
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AdditionalButtonStatus status = 6;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * button-当前状态
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AdditionalButtonStatus status = 6;</code>
     * @return The status.
     */
    @java.lang.Override
    public com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStatus getStatus() {
      @SuppressWarnings("deprecation")
      com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStatus result = com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStatus.valueOf(status_);
      return result == null ? com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStatus.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * button-当前状态
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AdditionalButtonStatus status = 6;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(com.bapis.bilibili.app.dynamic.v2.AdditionalButtonStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * button-当前状态
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.AdditionalButtonStatus status = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bilibili.app.dynamic.v2.AdditionalButton)
  }

  // @@protoc_insertion_point(class_scope:bilibili.app.dynamic.v2.AdditionalButton)
  private static final com.bapis.bilibili.app.dynamic.v2.AdditionalButton DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bapis.bilibili.app.dynamic.v2.AdditionalButton();
  }

  public static com.bapis.bilibili.app.dynamic.v2.AdditionalButton getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AdditionalButton>
      PARSER = new com.google.protobuf.AbstractParser<AdditionalButton>() {
    @java.lang.Override
    public AdditionalButton parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AdditionalButton(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AdditionalButton> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AdditionalButton> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bapis.bilibili.app.dynamic.v2.AdditionalButton getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

