// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/app/dynamic/v2/dynamic.proto

package com.bapis.bilibili.app.dynamic.v2;

/**
 * <pre>
 * Description 文本描述
 * </pre>
 *
 * Protobuf type {@code bilibili.app.dynamic.v2.Description}
 */
public final class Description extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bilibili.app.dynamic.v2.Description)
    DescriptionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Description.newBuilder() to construct.
  private Description(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Description() {
    text_ = "";
    type_ = 0;
    uri_ = "";
    emojiType_ = 0;
    goodsType_ = "";
    iconUrl_ = "";
    iconName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Description();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Description(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            text_ = s;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            uri_ = s;
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            emojiType_ = rawValue;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            goodsType_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            iconUrl_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            iconName_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bapis.bilibili.app.dynamic.v2.DynamicOuterClass.internal_static_bilibili_app_dynamic_v2_Description_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bapis.bilibili.app.dynamic.v2.DynamicOuterClass.internal_static_bilibili_app_dynamic_v2_Description_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bapis.bilibili.app.dynamic.v2.Description.class, com.bapis.bilibili.app.dynamic.v2.Description.Builder.class);
  }

  public static final int TEXT_FIELD_NUMBER = 1;
  private volatile java.lang.Object text_;
  /**
   * <pre>
   * 文本内容
   * </pre>
   *
   * <code>string text = 1;</code>
   * @return The text.
   */
  @java.lang.Override
  public java.lang.String getText() {
    java.lang.Object ref = text_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      text_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 文本内容
   * </pre>
   *
   * <code>string text = 1;</code>
   * @return The bytes for text.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTextBytes() {
    java.lang.Object ref = text_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      text_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 2;
  private int type_;
  /**
   * <pre>
   * 文本类型
   * </pre>
   *
   * <code>.bilibili.app.dynamic.v2.DescType type = 2;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <pre>
   * 文本类型
   * </pre>
   *
   * <code>.bilibili.app.dynamic.v2.DescType type = 2;</code>
   * @return The type.
   */
  @java.lang.Override public com.bapis.bilibili.app.dynamic.v2.DescType getType() {
    @SuppressWarnings("deprecation")
    com.bapis.bilibili.app.dynamic.v2.DescType result = com.bapis.bilibili.app.dynamic.v2.DescType.valueOf(type_);
    return result == null ? com.bapis.bilibili.app.dynamic.v2.DescType.UNRECOGNIZED : result;
  }

  public static final int URI_FIELD_NUMBER = 3;
  private volatile java.lang.Object uri_;
  /**
   * <pre>
   * 点击跳转链接
   * </pre>
   *
   * <code>string uri = 3;</code>
   * @return The uri.
   */
  @java.lang.Override
  public java.lang.String getUri() {
    java.lang.Object ref = uri_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      uri_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 点击跳转链接
   * </pre>
   *
   * <code>string uri = 3;</code>
   * @return The bytes for uri.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUriBytes() {
    java.lang.Object ref = uri_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uri_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMOJI_TYPE_FIELD_NUMBER = 4;
  private int emojiType_;
  /**
   * <pre>
   * emoji类型
   * </pre>
   *
   * <code>.bilibili.app.dynamic.v2.EmojiType emoji_type = 4;</code>
   * @return The enum numeric value on the wire for emojiType.
   */
  @java.lang.Override public int getEmojiTypeValue() {
    return emojiType_;
  }
  /**
   * <pre>
   * emoji类型
   * </pre>
   *
   * <code>.bilibili.app.dynamic.v2.EmojiType emoji_type = 4;</code>
   * @return The emojiType.
   */
  @java.lang.Override public com.bapis.bilibili.app.dynamic.v2.EmojiType getEmojiType() {
    @SuppressWarnings("deprecation")
    com.bapis.bilibili.app.dynamic.v2.EmojiType result = com.bapis.bilibili.app.dynamic.v2.EmojiType.valueOf(emojiType_);
    return result == null ? com.bapis.bilibili.app.dynamic.v2.EmojiType.UNRECOGNIZED : result;
  }

  public static final int GOODS_TYPE_FIELD_NUMBER = 5;
  private volatile java.lang.Object goodsType_;
  /**
   * <pre>
   * 商品类型
   * </pre>
   *
   * <code>string goods_type = 5;</code>
   * @return The goodsType.
   */
  @java.lang.Override
  public java.lang.String getGoodsType() {
    java.lang.Object ref = goodsType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      goodsType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 商品类型
   * </pre>
   *
   * <code>string goods_type = 5;</code>
   * @return The bytes for goodsType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGoodsTypeBytes() {
    java.lang.Object ref = goodsType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      goodsType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ICON_URL_FIELD_NUMBER = 6;
  private volatile java.lang.Object iconUrl_;
  /**
   * <pre>
   * 前置Icon
   * </pre>
   *
   * <code>string icon_url = 6;</code>
   * @return The iconUrl.
   */
  @java.lang.Override
  public java.lang.String getIconUrl() {
    java.lang.Object ref = iconUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      iconUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 前置Icon
   * </pre>
   *
   * <code>string icon_url = 6;</code>
   * @return The bytes for iconUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIconUrlBytes() {
    java.lang.Object ref = iconUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      iconUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ICON_NAME_FIELD_NUMBER = 7;
  private volatile java.lang.Object iconName_;
  /**
   * <pre>
   * icon_name
   * </pre>
   *
   * <code>string icon_name = 7;</code>
   * @return The iconName.
   */
  @java.lang.Override
  public java.lang.String getIconName() {
    java.lang.Object ref = iconName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      iconName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * icon_name
   * </pre>
   *
   * <code>string icon_name = 7;</code>
   * @return The bytes for iconName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIconNameBytes() {
    java.lang.Object ref = iconName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      iconName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTextBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, text_);
    }
    if (type_ != com.bapis.bilibili.app.dynamic.v2.DescType.desc_type_none.getNumber()) {
      output.writeEnum(2, type_);
    }
    if (!getUriBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, uri_);
    }
    if (emojiType_ != com.bapis.bilibili.app.dynamic.v2.EmojiType.emoji_none.getNumber()) {
      output.writeEnum(4, emojiType_);
    }
    if (!getGoodsTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, goodsType_);
    }
    if (!getIconUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, iconUrl_);
    }
    if (!getIconNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, iconName_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTextBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, text_);
    }
    if (type_ != com.bapis.bilibili.app.dynamic.v2.DescType.desc_type_none.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, type_);
    }
    if (!getUriBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, uri_);
    }
    if (emojiType_ != com.bapis.bilibili.app.dynamic.v2.EmojiType.emoji_none.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, emojiType_);
    }
    if (!getGoodsTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, goodsType_);
    }
    if (!getIconUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, iconUrl_);
    }
    if (!getIconNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, iconName_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bapis.bilibili.app.dynamic.v2.Description)) {
      return super.equals(obj);
    }
    com.bapis.bilibili.app.dynamic.v2.Description other = (com.bapis.bilibili.app.dynamic.v2.Description) obj;

    if (!getText()
        .equals(other.getText())) return false;
    if (type_ != other.type_) return false;
    if (!getUri()
        .equals(other.getUri())) return false;
    if (emojiType_ != other.emojiType_) return false;
    if (!getGoodsType()
        .equals(other.getGoodsType())) return false;
    if (!getIconUrl()
        .equals(other.getIconUrl())) return false;
    if (!getIconName()
        .equals(other.getIconName())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TEXT_FIELD_NUMBER;
    hash = (53 * hash) + getText().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + URI_FIELD_NUMBER;
    hash = (53 * hash) + getUri().hashCode();
    hash = (37 * hash) + EMOJI_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + emojiType_;
    hash = (37 * hash) + GOODS_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getGoodsType().hashCode();
    hash = (37 * hash) + ICON_URL_FIELD_NUMBER;
    hash = (53 * hash) + getIconUrl().hashCode();
    hash = (37 * hash) + ICON_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getIconName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bapis.bilibili.app.dynamic.v2.Description parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bapis.bilibili.app.dynamic.v2.Description parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bapis.bilibili.app.dynamic.v2.Description parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bapis.bilibili.app.dynamic.v2.Description parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bapis.bilibili.app.dynamic.v2.Description parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bapis.bilibili.app.dynamic.v2.Description parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bapis.bilibili.app.dynamic.v2.Description parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bapis.bilibili.app.dynamic.v2.Description parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bapis.bilibili.app.dynamic.v2.Description parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bapis.bilibili.app.dynamic.v2.Description parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bapis.bilibili.app.dynamic.v2.Description parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bapis.bilibili.app.dynamic.v2.Description parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bapis.bilibili.app.dynamic.v2.Description prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Description 文本描述
   * </pre>
   *
   * Protobuf type {@code bilibili.app.dynamic.v2.Description}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bilibili.app.dynamic.v2.Description)
      com.bapis.bilibili.app.dynamic.v2.DescriptionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bapis.bilibili.app.dynamic.v2.DynamicOuterClass.internal_static_bilibili_app_dynamic_v2_Description_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bapis.bilibili.app.dynamic.v2.DynamicOuterClass.internal_static_bilibili_app_dynamic_v2_Description_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bapis.bilibili.app.dynamic.v2.Description.class, com.bapis.bilibili.app.dynamic.v2.Description.Builder.class);
    }

    // Construct using com.bapis.bilibili.app.dynamic.v2.Description.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      text_ = "";

      type_ = 0;

      uri_ = "";

      emojiType_ = 0;

      goodsType_ = "";

      iconUrl_ = "";

      iconName_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bapis.bilibili.app.dynamic.v2.DynamicOuterClass.internal_static_bilibili_app_dynamic_v2_Description_descriptor;
    }

    @java.lang.Override
    public com.bapis.bilibili.app.dynamic.v2.Description getDefaultInstanceForType() {
      return com.bapis.bilibili.app.dynamic.v2.Description.getDefaultInstance();
    }

    @java.lang.Override
    public com.bapis.bilibili.app.dynamic.v2.Description build() {
      com.bapis.bilibili.app.dynamic.v2.Description result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bapis.bilibili.app.dynamic.v2.Description buildPartial() {
      com.bapis.bilibili.app.dynamic.v2.Description result = new com.bapis.bilibili.app.dynamic.v2.Description(this);
      result.text_ = text_;
      result.type_ = type_;
      result.uri_ = uri_;
      result.emojiType_ = emojiType_;
      result.goodsType_ = goodsType_;
      result.iconUrl_ = iconUrl_;
      result.iconName_ = iconName_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bapis.bilibili.app.dynamic.v2.Description) {
        return mergeFrom((com.bapis.bilibili.app.dynamic.v2.Description)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bapis.bilibili.app.dynamic.v2.Description other) {
      if (other == com.bapis.bilibili.app.dynamic.v2.Description.getDefaultInstance()) return this;
      if (!other.getText().isEmpty()) {
        text_ = other.text_;
        onChanged();
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (!other.getUri().isEmpty()) {
        uri_ = other.uri_;
        onChanged();
      }
      if (other.emojiType_ != 0) {
        setEmojiTypeValue(other.getEmojiTypeValue());
      }
      if (!other.getGoodsType().isEmpty()) {
        goodsType_ = other.goodsType_;
        onChanged();
      }
      if (!other.getIconUrl().isEmpty()) {
        iconUrl_ = other.iconUrl_;
        onChanged();
      }
      if (!other.getIconName().isEmpty()) {
        iconName_ = other.iconName_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bapis.bilibili.app.dynamic.v2.Description parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bapis.bilibili.app.dynamic.v2.Description) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object text_ = "";
    /**
     * <pre>
     * 文本内容
     * </pre>
     *
     * <code>string text = 1;</code>
     * @return The text.
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 文本内容
     * </pre>
     *
     * <code>string text = 1;</code>
     * @return The bytes for text.
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 文本内容
     * </pre>
     *
     * <code>string text = 1;</code>
     * @param value The text to set.
     * @return This builder for chaining.
     */
    public Builder setText(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      text_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 文本内容
     * </pre>
     *
     * <code>string text = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearText() {
      
      text_ = getDefaultInstance().getText();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 文本内容
     * </pre>
     *
     * <code>string text = 1;</code>
     * @param value The bytes for text to set.
     * @return This builder for chaining.
     */
    public Builder setTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      text_ = value;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <pre>
     * 文本类型
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.DescType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * 文本类型
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.DescType type = 2;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 文本类型
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.DescType type = 2;</code>
     * @return The type.
     */
    @java.lang.Override
    public com.bapis.bilibili.app.dynamic.v2.DescType getType() {
      @SuppressWarnings("deprecation")
      com.bapis.bilibili.app.dynamic.v2.DescType result = com.bapis.bilibili.app.dynamic.v2.DescType.valueOf(type_);
      return result == null ? com.bapis.bilibili.app.dynamic.v2.DescType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 文本类型
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.DescType type = 2;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(com.bapis.bilibili.app.dynamic.v2.DescType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 文本类型
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.DescType type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object uri_ = "";
    /**
     * <pre>
     * 点击跳转链接
     * </pre>
     *
     * <code>string uri = 3;</code>
     * @return The uri.
     */
    public java.lang.String getUri() {
      java.lang.Object ref = uri_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uri_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 点击跳转链接
     * </pre>
     *
     * <code>string uri = 3;</code>
     * @return The bytes for uri.
     */
    public com.google.protobuf.ByteString
        getUriBytes() {
      java.lang.Object ref = uri_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 点击跳转链接
     * </pre>
     *
     * <code>string uri = 3;</code>
     * @param value The uri to set.
     * @return This builder for chaining.
     */
    public Builder setUri(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      uri_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 点击跳转链接
     * </pre>
     *
     * <code>string uri = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUri() {
      
      uri_ = getDefaultInstance().getUri();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 点击跳转链接
     * </pre>
     *
     * <code>string uri = 3;</code>
     * @param value The bytes for uri to set.
     * @return This builder for chaining.
     */
    public Builder setUriBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      uri_ = value;
      onChanged();
      return this;
    }

    private int emojiType_ = 0;
    /**
     * <pre>
     * emoji类型
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.EmojiType emoji_type = 4;</code>
     * @return The enum numeric value on the wire for emojiType.
     */
    @java.lang.Override public int getEmojiTypeValue() {
      return emojiType_;
    }
    /**
     * <pre>
     * emoji类型
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.EmojiType emoji_type = 4;</code>
     * @param value The enum numeric value on the wire for emojiType to set.
     * @return This builder for chaining.
     */
    public Builder setEmojiTypeValue(int value) {
      
      emojiType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * emoji类型
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.EmojiType emoji_type = 4;</code>
     * @return The emojiType.
     */
    @java.lang.Override
    public com.bapis.bilibili.app.dynamic.v2.EmojiType getEmojiType() {
      @SuppressWarnings("deprecation")
      com.bapis.bilibili.app.dynamic.v2.EmojiType result = com.bapis.bilibili.app.dynamic.v2.EmojiType.valueOf(emojiType_);
      return result == null ? com.bapis.bilibili.app.dynamic.v2.EmojiType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * emoji类型
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.EmojiType emoji_type = 4;</code>
     * @param value The emojiType to set.
     * @return This builder for chaining.
     */
    public Builder setEmojiType(com.bapis.bilibili.app.dynamic.v2.EmojiType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      emojiType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * emoji类型
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.EmojiType emoji_type = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmojiType() {
      
      emojiType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object goodsType_ = "";
    /**
     * <pre>
     * 商品类型
     * </pre>
     *
     * <code>string goods_type = 5;</code>
     * @return The goodsType.
     */
    public java.lang.String getGoodsType() {
      java.lang.Object ref = goodsType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        goodsType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 商品类型
     * </pre>
     *
     * <code>string goods_type = 5;</code>
     * @return The bytes for goodsType.
     */
    public com.google.protobuf.ByteString
        getGoodsTypeBytes() {
      java.lang.Object ref = goodsType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        goodsType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 商品类型
     * </pre>
     *
     * <code>string goods_type = 5;</code>
     * @param value The goodsType to set.
     * @return This builder for chaining.
     */
    public Builder setGoodsType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      goodsType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 商品类型
     * </pre>
     *
     * <code>string goods_type = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearGoodsType() {
      
      goodsType_ = getDefaultInstance().getGoodsType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 商品类型
     * </pre>
     *
     * <code>string goods_type = 5;</code>
     * @param value The bytes for goodsType to set.
     * @return This builder for chaining.
     */
    public Builder setGoodsTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      goodsType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object iconUrl_ = "";
    /**
     * <pre>
     * 前置Icon
     * </pre>
     *
     * <code>string icon_url = 6;</code>
     * @return The iconUrl.
     */
    public java.lang.String getIconUrl() {
      java.lang.Object ref = iconUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        iconUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 前置Icon
     * </pre>
     *
     * <code>string icon_url = 6;</code>
     * @return The bytes for iconUrl.
     */
    public com.google.protobuf.ByteString
        getIconUrlBytes() {
      java.lang.Object ref = iconUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        iconUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 前置Icon
     * </pre>
     *
     * <code>string icon_url = 6;</code>
     * @param value The iconUrl to set.
     * @return This builder for chaining.
     */
    public Builder setIconUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      iconUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 前置Icon
     * </pre>
     *
     * <code>string icon_url = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearIconUrl() {
      
      iconUrl_ = getDefaultInstance().getIconUrl();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 前置Icon
     * </pre>
     *
     * <code>string icon_url = 6;</code>
     * @param value The bytes for iconUrl to set.
     * @return This builder for chaining.
     */
    public Builder setIconUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      iconUrl_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object iconName_ = "";
    /**
     * <pre>
     * icon_name
     * </pre>
     *
     * <code>string icon_name = 7;</code>
     * @return The iconName.
     */
    public java.lang.String getIconName() {
      java.lang.Object ref = iconName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        iconName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * icon_name
     * </pre>
     *
     * <code>string icon_name = 7;</code>
     * @return The bytes for iconName.
     */
    public com.google.protobuf.ByteString
        getIconNameBytes() {
      java.lang.Object ref = iconName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        iconName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * icon_name
     * </pre>
     *
     * <code>string icon_name = 7;</code>
     * @param value The iconName to set.
     * @return This builder for chaining.
     */
    public Builder setIconName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      iconName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * icon_name
     * </pre>
     *
     * <code>string icon_name = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearIconName() {
      
      iconName_ = getDefaultInstance().getIconName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * icon_name
     * </pre>
     *
     * <code>string icon_name = 7;</code>
     * @param value The bytes for iconName to set.
     * @return This builder for chaining.
     */
    public Builder setIconNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      iconName_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bilibili.app.dynamic.v2.Description)
  }

  // @@protoc_insertion_point(class_scope:bilibili.app.dynamic.v2.Description)
  private static final com.bapis.bilibili.app.dynamic.v2.Description DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bapis.bilibili.app.dynamic.v2.Description();
  }

  public static com.bapis.bilibili.app.dynamic.v2.Description getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Description>
      PARSER = new com.google.protobuf.AbstractParser<Description>() {
    @java.lang.Override
    public Description parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Description(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Description> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Description> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bapis.bilibili.app.dynamic.v2.Description getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

