// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/app/dynamic/v2/dynamic.proto

package com.bapis.bilibili.app.dynamic.v2;

/**
 * <pre>
 * DynVideoReqReply 动态视频页返回值
 * </pre>
 *
 * Protobuf type {@code bilibili.app.dynamic.v2.DynVideoReply}
 */
public final class DynVideoReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bilibili.app.dynamic.v2.DynVideoReply)
    DynVideoReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DynVideoReply.newBuilder() to construct.
  private DynVideoReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DynVideoReply() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DynVideoReply();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DynVideoReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.bapis.bilibili.app.dynamic.v2.CardVideoDynList.Builder subBuilder = null;
            if (dynamicList_ != null) {
              subBuilder = dynamicList_.toBuilder();
            }
            dynamicList_ = input.readMessage(com.bapis.bilibili.app.dynamic.v2.CardVideoDynList.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dynamicList_);
              dynamicList_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.bapis.bilibili.app.dynamic.v2.CardVideoUpList.Builder subBuilder = null;
            if (videoUpList_ != null) {
              subBuilder = videoUpList_.toBuilder();
            }
            videoUpList_ = input.readMessage(com.bapis.bilibili.app.dynamic.v2.CardVideoUpList.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(videoUpList_);
              videoUpList_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.bapis.bilibili.app.dynamic.v2.CardVideoFollowList.Builder subBuilder = null;
            if (videoFollowList_ != null) {
              subBuilder = videoFollowList_.toBuilder();
            }
            videoFollowList_ = input.readMessage(com.bapis.bilibili.app.dynamic.v2.CardVideoFollowList.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(videoFollowList_);
              videoFollowList_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bapis.bilibili.app.dynamic.v2.DynamicOuterClass.internal_static_bilibili_app_dynamic_v2_DynVideoReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bapis.bilibili.app.dynamic.v2.DynamicOuterClass.internal_static_bilibili_app_dynamic_v2_DynVideoReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bapis.bilibili.app.dynamic.v2.DynVideoReply.class, com.bapis.bilibili.app.dynamic.v2.DynVideoReply.Builder.class);
  }

  public static final int DYNAMIC_LIST_FIELD_NUMBER = 1;
  private com.bapis.bilibili.app.dynamic.v2.CardVideoDynList dynamicList_;
  /**
   * <pre>
   * 卡片列表
   * </pre>
   *
   * <code>.bilibili.app.dynamic.v2.CardVideoDynList dynamic_list = 1;</code>
   * @return Whether the dynamicList field is set.
   */
  @java.lang.Override
  public boolean hasDynamicList() {
    return dynamicList_ != null;
  }
  /**
   * <pre>
   * 卡片列表
   * </pre>
   *
   * <code>.bilibili.app.dynamic.v2.CardVideoDynList dynamic_list = 1;</code>
   * @return The dynamicList.
   */
  @java.lang.Override
  public com.bapis.bilibili.app.dynamic.v2.CardVideoDynList getDynamicList() {
    return dynamicList_ == null ? com.bapis.bilibili.app.dynamic.v2.CardVideoDynList.getDefaultInstance() : dynamicList_;
  }
  /**
   * <pre>
   * 卡片列表
   * </pre>
   *
   * <code>.bilibili.app.dynamic.v2.CardVideoDynList dynamic_list = 1;</code>
   */
  @java.lang.Override
  public com.bapis.bilibili.app.dynamic.v2.CardVideoDynListOrBuilder getDynamicListOrBuilder() {
    return getDynamicList();
  }

  public static final int VIDEO_UP_LIST_FIELD_NUMBER = 2;
  private com.bapis.bilibili.app.dynamic.v2.CardVideoUpList videoUpList_;
  /**
   * <code>.bilibili.app.dynamic.v2.CardVideoUpList video_up_list = 2;</code>
   * @return Whether the videoUpList field is set.
   */
  @java.lang.Override
  public boolean hasVideoUpList() {
    return videoUpList_ != null;
  }
  /**
   * <code>.bilibili.app.dynamic.v2.CardVideoUpList video_up_list = 2;</code>
   * @return The videoUpList.
   */
  @java.lang.Override
  public com.bapis.bilibili.app.dynamic.v2.CardVideoUpList getVideoUpList() {
    return videoUpList_ == null ? com.bapis.bilibili.app.dynamic.v2.CardVideoUpList.getDefaultInstance() : videoUpList_;
  }
  /**
   * <code>.bilibili.app.dynamic.v2.CardVideoUpList video_up_list = 2;</code>
   */
  @java.lang.Override
  public com.bapis.bilibili.app.dynamic.v2.CardVideoUpListOrBuilder getVideoUpListOrBuilder() {
    return getVideoUpList();
  }

  public static final int VIDEO_FOLLOW_LIST_FIELD_NUMBER = 3;
  private com.bapis.bilibili.app.dynamic.v2.CardVideoFollowList videoFollowList_;
  /**
   * <code>.bilibili.app.dynamic.v2.CardVideoFollowList video_follow_list = 3;</code>
   * @return Whether the videoFollowList field is set.
   */
  @java.lang.Override
  public boolean hasVideoFollowList() {
    return videoFollowList_ != null;
  }
  /**
   * <code>.bilibili.app.dynamic.v2.CardVideoFollowList video_follow_list = 3;</code>
   * @return The videoFollowList.
   */
  @java.lang.Override
  public com.bapis.bilibili.app.dynamic.v2.CardVideoFollowList getVideoFollowList() {
    return videoFollowList_ == null ? com.bapis.bilibili.app.dynamic.v2.CardVideoFollowList.getDefaultInstance() : videoFollowList_;
  }
  /**
   * <code>.bilibili.app.dynamic.v2.CardVideoFollowList video_follow_list = 3;</code>
   */
  @java.lang.Override
  public com.bapis.bilibili.app.dynamic.v2.CardVideoFollowListOrBuilder getVideoFollowListOrBuilder() {
    return getVideoFollowList();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (dynamicList_ != null) {
      output.writeMessage(1, getDynamicList());
    }
    if (videoUpList_ != null) {
      output.writeMessage(2, getVideoUpList());
    }
    if (videoFollowList_ != null) {
      output.writeMessage(3, getVideoFollowList());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (dynamicList_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getDynamicList());
    }
    if (videoUpList_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getVideoUpList());
    }
    if (videoFollowList_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getVideoFollowList());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bapis.bilibili.app.dynamic.v2.DynVideoReply)) {
      return super.equals(obj);
    }
    com.bapis.bilibili.app.dynamic.v2.DynVideoReply other = (com.bapis.bilibili.app.dynamic.v2.DynVideoReply) obj;

    if (hasDynamicList() != other.hasDynamicList()) return false;
    if (hasDynamicList()) {
      if (!getDynamicList()
          .equals(other.getDynamicList())) return false;
    }
    if (hasVideoUpList() != other.hasVideoUpList()) return false;
    if (hasVideoUpList()) {
      if (!getVideoUpList()
          .equals(other.getVideoUpList())) return false;
    }
    if (hasVideoFollowList() != other.hasVideoFollowList()) return false;
    if (hasVideoFollowList()) {
      if (!getVideoFollowList()
          .equals(other.getVideoFollowList())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDynamicList()) {
      hash = (37 * hash) + DYNAMIC_LIST_FIELD_NUMBER;
      hash = (53 * hash) + getDynamicList().hashCode();
    }
    if (hasVideoUpList()) {
      hash = (37 * hash) + VIDEO_UP_LIST_FIELD_NUMBER;
      hash = (53 * hash) + getVideoUpList().hashCode();
    }
    if (hasVideoFollowList()) {
      hash = (37 * hash) + VIDEO_FOLLOW_LIST_FIELD_NUMBER;
      hash = (53 * hash) + getVideoFollowList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bapis.bilibili.app.dynamic.v2.DynVideoReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bapis.bilibili.app.dynamic.v2.DynVideoReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bapis.bilibili.app.dynamic.v2.DynVideoReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bapis.bilibili.app.dynamic.v2.DynVideoReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bapis.bilibili.app.dynamic.v2.DynVideoReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bapis.bilibili.app.dynamic.v2.DynVideoReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bapis.bilibili.app.dynamic.v2.DynVideoReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bapis.bilibili.app.dynamic.v2.DynVideoReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bapis.bilibili.app.dynamic.v2.DynVideoReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bapis.bilibili.app.dynamic.v2.DynVideoReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bapis.bilibili.app.dynamic.v2.DynVideoReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bapis.bilibili.app.dynamic.v2.DynVideoReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bapis.bilibili.app.dynamic.v2.DynVideoReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * DynVideoReqReply 动态视频页返回值
   * </pre>
   *
   * Protobuf type {@code bilibili.app.dynamic.v2.DynVideoReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bilibili.app.dynamic.v2.DynVideoReply)
      com.bapis.bilibili.app.dynamic.v2.DynVideoReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bapis.bilibili.app.dynamic.v2.DynamicOuterClass.internal_static_bilibili_app_dynamic_v2_DynVideoReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bapis.bilibili.app.dynamic.v2.DynamicOuterClass.internal_static_bilibili_app_dynamic_v2_DynVideoReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bapis.bilibili.app.dynamic.v2.DynVideoReply.class, com.bapis.bilibili.app.dynamic.v2.DynVideoReply.Builder.class);
    }

    // Construct using com.bapis.bilibili.app.dynamic.v2.DynVideoReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (dynamicListBuilder_ == null) {
        dynamicList_ = null;
      } else {
        dynamicList_ = null;
        dynamicListBuilder_ = null;
      }
      if (videoUpListBuilder_ == null) {
        videoUpList_ = null;
      } else {
        videoUpList_ = null;
        videoUpListBuilder_ = null;
      }
      if (videoFollowListBuilder_ == null) {
        videoFollowList_ = null;
      } else {
        videoFollowList_ = null;
        videoFollowListBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bapis.bilibili.app.dynamic.v2.DynamicOuterClass.internal_static_bilibili_app_dynamic_v2_DynVideoReply_descriptor;
    }

    @java.lang.Override
    public com.bapis.bilibili.app.dynamic.v2.DynVideoReply getDefaultInstanceForType() {
      return com.bapis.bilibili.app.dynamic.v2.DynVideoReply.getDefaultInstance();
    }

    @java.lang.Override
    public com.bapis.bilibili.app.dynamic.v2.DynVideoReply build() {
      com.bapis.bilibili.app.dynamic.v2.DynVideoReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bapis.bilibili.app.dynamic.v2.DynVideoReply buildPartial() {
      com.bapis.bilibili.app.dynamic.v2.DynVideoReply result = new com.bapis.bilibili.app.dynamic.v2.DynVideoReply(this);
      if (dynamicListBuilder_ == null) {
        result.dynamicList_ = dynamicList_;
      } else {
        result.dynamicList_ = dynamicListBuilder_.build();
      }
      if (videoUpListBuilder_ == null) {
        result.videoUpList_ = videoUpList_;
      } else {
        result.videoUpList_ = videoUpListBuilder_.build();
      }
      if (videoFollowListBuilder_ == null) {
        result.videoFollowList_ = videoFollowList_;
      } else {
        result.videoFollowList_ = videoFollowListBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bapis.bilibili.app.dynamic.v2.DynVideoReply) {
        return mergeFrom((com.bapis.bilibili.app.dynamic.v2.DynVideoReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bapis.bilibili.app.dynamic.v2.DynVideoReply other) {
      if (other == com.bapis.bilibili.app.dynamic.v2.DynVideoReply.getDefaultInstance()) return this;
      if (other.hasDynamicList()) {
        mergeDynamicList(other.getDynamicList());
      }
      if (other.hasVideoUpList()) {
        mergeVideoUpList(other.getVideoUpList());
      }
      if (other.hasVideoFollowList()) {
        mergeVideoFollowList(other.getVideoFollowList());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bapis.bilibili.app.dynamic.v2.DynVideoReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bapis.bilibili.app.dynamic.v2.DynVideoReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.bapis.bilibili.app.dynamic.v2.CardVideoDynList dynamicList_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.bapis.bilibili.app.dynamic.v2.CardVideoDynList, com.bapis.bilibili.app.dynamic.v2.CardVideoDynList.Builder, com.bapis.bilibili.app.dynamic.v2.CardVideoDynListOrBuilder> dynamicListBuilder_;
    /**
     * <pre>
     * 卡片列表
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.CardVideoDynList dynamic_list = 1;</code>
     * @return Whether the dynamicList field is set.
     */
    public boolean hasDynamicList() {
      return dynamicListBuilder_ != null || dynamicList_ != null;
    }
    /**
     * <pre>
     * 卡片列表
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.CardVideoDynList dynamic_list = 1;</code>
     * @return The dynamicList.
     */
    public com.bapis.bilibili.app.dynamic.v2.CardVideoDynList getDynamicList() {
      if (dynamicListBuilder_ == null) {
        return dynamicList_ == null ? com.bapis.bilibili.app.dynamic.v2.CardVideoDynList.getDefaultInstance() : dynamicList_;
      } else {
        return dynamicListBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 卡片列表
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.CardVideoDynList dynamic_list = 1;</code>
     */
    public Builder setDynamicList(com.bapis.bilibili.app.dynamic.v2.CardVideoDynList value) {
      if (dynamicListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dynamicList_ = value;
        onChanged();
      } else {
        dynamicListBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 卡片列表
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.CardVideoDynList dynamic_list = 1;</code>
     */
    public Builder setDynamicList(
        com.bapis.bilibili.app.dynamic.v2.CardVideoDynList.Builder builderForValue) {
      if (dynamicListBuilder_ == null) {
        dynamicList_ = builderForValue.build();
        onChanged();
      } else {
        dynamicListBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 卡片列表
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.CardVideoDynList dynamic_list = 1;</code>
     */
    public Builder mergeDynamicList(com.bapis.bilibili.app.dynamic.v2.CardVideoDynList value) {
      if (dynamicListBuilder_ == null) {
        if (dynamicList_ != null) {
          dynamicList_ =
            com.bapis.bilibili.app.dynamic.v2.CardVideoDynList.newBuilder(dynamicList_).mergeFrom(value).buildPartial();
        } else {
          dynamicList_ = value;
        }
        onChanged();
      } else {
        dynamicListBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 卡片列表
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.CardVideoDynList dynamic_list = 1;</code>
     */
    public Builder clearDynamicList() {
      if (dynamicListBuilder_ == null) {
        dynamicList_ = null;
        onChanged();
      } else {
        dynamicList_ = null;
        dynamicListBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 卡片列表
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.CardVideoDynList dynamic_list = 1;</code>
     */
    public com.bapis.bilibili.app.dynamic.v2.CardVideoDynList.Builder getDynamicListBuilder() {
      
      onChanged();
      return getDynamicListFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 卡片列表
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.CardVideoDynList dynamic_list = 1;</code>
     */
    public com.bapis.bilibili.app.dynamic.v2.CardVideoDynListOrBuilder getDynamicListOrBuilder() {
      if (dynamicListBuilder_ != null) {
        return dynamicListBuilder_.getMessageOrBuilder();
      } else {
        return dynamicList_ == null ?
            com.bapis.bilibili.app.dynamic.v2.CardVideoDynList.getDefaultInstance() : dynamicList_;
      }
    }
    /**
     * <pre>
     * 卡片列表
     * </pre>
     *
     * <code>.bilibili.app.dynamic.v2.CardVideoDynList dynamic_list = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.bapis.bilibili.app.dynamic.v2.CardVideoDynList, com.bapis.bilibili.app.dynamic.v2.CardVideoDynList.Builder, com.bapis.bilibili.app.dynamic.v2.CardVideoDynListOrBuilder> 
        getDynamicListFieldBuilder() {
      if (dynamicListBuilder_ == null) {
        dynamicListBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.bapis.bilibili.app.dynamic.v2.CardVideoDynList, com.bapis.bilibili.app.dynamic.v2.CardVideoDynList.Builder, com.bapis.bilibili.app.dynamic.v2.CardVideoDynListOrBuilder>(
                getDynamicList(),
                getParentForChildren(),
                isClean());
        dynamicList_ = null;
      }
      return dynamicListBuilder_;
    }

    private com.bapis.bilibili.app.dynamic.v2.CardVideoUpList videoUpList_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.bapis.bilibili.app.dynamic.v2.CardVideoUpList, com.bapis.bilibili.app.dynamic.v2.CardVideoUpList.Builder, com.bapis.bilibili.app.dynamic.v2.CardVideoUpListOrBuilder> videoUpListBuilder_;
    /**
     * <code>.bilibili.app.dynamic.v2.CardVideoUpList video_up_list = 2;</code>
     * @return Whether the videoUpList field is set.
     */
    public boolean hasVideoUpList() {
      return videoUpListBuilder_ != null || videoUpList_ != null;
    }
    /**
     * <code>.bilibili.app.dynamic.v2.CardVideoUpList video_up_list = 2;</code>
     * @return The videoUpList.
     */
    public com.bapis.bilibili.app.dynamic.v2.CardVideoUpList getVideoUpList() {
      if (videoUpListBuilder_ == null) {
        return videoUpList_ == null ? com.bapis.bilibili.app.dynamic.v2.CardVideoUpList.getDefaultInstance() : videoUpList_;
      } else {
        return videoUpListBuilder_.getMessage();
      }
    }
    /**
     * <code>.bilibili.app.dynamic.v2.CardVideoUpList video_up_list = 2;</code>
     */
    public Builder setVideoUpList(com.bapis.bilibili.app.dynamic.v2.CardVideoUpList value) {
      if (videoUpListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        videoUpList_ = value;
        onChanged();
      } else {
        videoUpListBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.bilibili.app.dynamic.v2.CardVideoUpList video_up_list = 2;</code>
     */
    public Builder setVideoUpList(
        com.bapis.bilibili.app.dynamic.v2.CardVideoUpList.Builder builderForValue) {
      if (videoUpListBuilder_ == null) {
        videoUpList_ = builderForValue.build();
        onChanged();
      } else {
        videoUpListBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.bilibili.app.dynamic.v2.CardVideoUpList video_up_list = 2;</code>
     */
    public Builder mergeVideoUpList(com.bapis.bilibili.app.dynamic.v2.CardVideoUpList value) {
      if (videoUpListBuilder_ == null) {
        if (videoUpList_ != null) {
          videoUpList_ =
            com.bapis.bilibili.app.dynamic.v2.CardVideoUpList.newBuilder(videoUpList_).mergeFrom(value).buildPartial();
        } else {
          videoUpList_ = value;
        }
        onChanged();
      } else {
        videoUpListBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.bilibili.app.dynamic.v2.CardVideoUpList video_up_list = 2;</code>
     */
    public Builder clearVideoUpList() {
      if (videoUpListBuilder_ == null) {
        videoUpList_ = null;
        onChanged();
      } else {
        videoUpList_ = null;
        videoUpListBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.bilibili.app.dynamic.v2.CardVideoUpList video_up_list = 2;</code>
     */
    public com.bapis.bilibili.app.dynamic.v2.CardVideoUpList.Builder getVideoUpListBuilder() {
      
      onChanged();
      return getVideoUpListFieldBuilder().getBuilder();
    }
    /**
     * <code>.bilibili.app.dynamic.v2.CardVideoUpList video_up_list = 2;</code>
     */
    public com.bapis.bilibili.app.dynamic.v2.CardVideoUpListOrBuilder getVideoUpListOrBuilder() {
      if (videoUpListBuilder_ != null) {
        return videoUpListBuilder_.getMessageOrBuilder();
      } else {
        return videoUpList_ == null ?
            com.bapis.bilibili.app.dynamic.v2.CardVideoUpList.getDefaultInstance() : videoUpList_;
      }
    }
    /**
     * <code>.bilibili.app.dynamic.v2.CardVideoUpList video_up_list = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.bapis.bilibili.app.dynamic.v2.CardVideoUpList, com.bapis.bilibili.app.dynamic.v2.CardVideoUpList.Builder, com.bapis.bilibili.app.dynamic.v2.CardVideoUpListOrBuilder> 
        getVideoUpListFieldBuilder() {
      if (videoUpListBuilder_ == null) {
        videoUpListBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.bapis.bilibili.app.dynamic.v2.CardVideoUpList, com.bapis.bilibili.app.dynamic.v2.CardVideoUpList.Builder, com.bapis.bilibili.app.dynamic.v2.CardVideoUpListOrBuilder>(
                getVideoUpList(),
                getParentForChildren(),
                isClean());
        videoUpList_ = null;
      }
      return videoUpListBuilder_;
    }

    private com.bapis.bilibili.app.dynamic.v2.CardVideoFollowList videoFollowList_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.bapis.bilibili.app.dynamic.v2.CardVideoFollowList, com.bapis.bilibili.app.dynamic.v2.CardVideoFollowList.Builder, com.bapis.bilibili.app.dynamic.v2.CardVideoFollowListOrBuilder> videoFollowListBuilder_;
    /**
     * <code>.bilibili.app.dynamic.v2.CardVideoFollowList video_follow_list = 3;</code>
     * @return Whether the videoFollowList field is set.
     */
    public boolean hasVideoFollowList() {
      return videoFollowListBuilder_ != null || videoFollowList_ != null;
    }
    /**
     * <code>.bilibili.app.dynamic.v2.CardVideoFollowList video_follow_list = 3;</code>
     * @return The videoFollowList.
     */
    public com.bapis.bilibili.app.dynamic.v2.CardVideoFollowList getVideoFollowList() {
      if (videoFollowListBuilder_ == null) {
        return videoFollowList_ == null ? com.bapis.bilibili.app.dynamic.v2.CardVideoFollowList.getDefaultInstance() : videoFollowList_;
      } else {
        return videoFollowListBuilder_.getMessage();
      }
    }
    /**
     * <code>.bilibili.app.dynamic.v2.CardVideoFollowList video_follow_list = 3;</code>
     */
    public Builder setVideoFollowList(com.bapis.bilibili.app.dynamic.v2.CardVideoFollowList value) {
      if (videoFollowListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        videoFollowList_ = value;
        onChanged();
      } else {
        videoFollowListBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.bilibili.app.dynamic.v2.CardVideoFollowList video_follow_list = 3;</code>
     */
    public Builder setVideoFollowList(
        com.bapis.bilibili.app.dynamic.v2.CardVideoFollowList.Builder builderForValue) {
      if (videoFollowListBuilder_ == null) {
        videoFollowList_ = builderForValue.build();
        onChanged();
      } else {
        videoFollowListBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.bilibili.app.dynamic.v2.CardVideoFollowList video_follow_list = 3;</code>
     */
    public Builder mergeVideoFollowList(com.bapis.bilibili.app.dynamic.v2.CardVideoFollowList value) {
      if (videoFollowListBuilder_ == null) {
        if (videoFollowList_ != null) {
          videoFollowList_ =
            com.bapis.bilibili.app.dynamic.v2.CardVideoFollowList.newBuilder(videoFollowList_).mergeFrom(value).buildPartial();
        } else {
          videoFollowList_ = value;
        }
        onChanged();
      } else {
        videoFollowListBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.bilibili.app.dynamic.v2.CardVideoFollowList video_follow_list = 3;</code>
     */
    public Builder clearVideoFollowList() {
      if (videoFollowListBuilder_ == null) {
        videoFollowList_ = null;
        onChanged();
      } else {
        videoFollowList_ = null;
        videoFollowListBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.bilibili.app.dynamic.v2.CardVideoFollowList video_follow_list = 3;</code>
     */
    public com.bapis.bilibili.app.dynamic.v2.CardVideoFollowList.Builder getVideoFollowListBuilder() {
      
      onChanged();
      return getVideoFollowListFieldBuilder().getBuilder();
    }
    /**
     * <code>.bilibili.app.dynamic.v2.CardVideoFollowList video_follow_list = 3;</code>
     */
    public com.bapis.bilibili.app.dynamic.v2.CardVideoFollowListOrBuilder getVideoFollowListOrBuilder() {
      if (videoFollowListBuilder_ != null) {
        return videoFollowListBuilder_.getMessageOrBuilder();
      } else {
        return videoFollowList_ == null ?
            com.bapis.bilibili.app.dynamic.v2.CardVideoFollowList.getDefaultInstance() : videoFollowList_;
      }
    }
    /**
     * <code>.bilibili.app.dynamic.v2.CardVideoFollowList video_follow_list = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.bapis.bilibili.app.dynamic.v2.CardVideoFollowList, com.bapis.bilibili.app.dynamic.v2.CardVideoFollowList.Builder, com.bapis.bilibili.app.dynamic.v2.CardVideoFollowListOrBuilder> 
        getVideoFollowListFieldBuilder() {
      if (videoFollowListBuilder_ == null) {
        videoFollowListBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.bapis.bilibili.app.dynamic.v2.CardVideoFollowList, com.bapis.bilibili.app.dynamic.v2.CardVideoFollowList.Builder, com.bapis.bilibili.app.dynamic.v2.CardVideoFollowListOrBuilder>(
                getVideoFollowList(),
                getParentForChildren(),
                isClean());
        videoFollowList_ = null;
      }
      return videoFollowListBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bilibili.app.dynamic.v2.DynVideoReply)
  }

  // @@protoc_insertion_point(class_scope:bilibili.app.dynamic.v2.DynVideoReply)
  private static final com.bapis.bilibili.app.dynamic.v2.DynVideoReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bapis.bilibili.app.dynamic.v2.DynVideoReply();
  }

  public static com.bapis.bilibili.app.dynamic.v2.DynVideoReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DynVideoReply>
      PARSER = new com.google.protobuf.AbstractParser<DynVideoReply>() {
    @java.lang.Override
    public DynVideoReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DynVideoReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DynVideoReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DynVideoReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bapis.bilibili.app.dynamic.v2.DynVideoReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

