// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/app/dynamic/v2/dynamic.proto

package com.bapis.bilibili.app.dynamic.v2;

public interface ModuleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bilibili.app.dynamic.v2.Module)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.bilibili.app.dynamic.v2.DynModuleType module_type = 1;</code>
   * @return The enum numeric value on the wire for moduleType.
   */
  int getModuleTypeValue();
  /**
   * <code>.bilibili.app.dynamic.v2.DynModuleType module_type = 1;</code>
   * @return The moduleType.
   */
  com.bapis.bilibili.app.dynamic.v2.DynModuleType getModuleType();

  /**
   * <code>.bilibili.app.dynamic.v2.ModuleAuthor module_author = 2;</code>
   * @return Whether the moduleAuthor field is set.
   */
  boolean hasModuleAuthor();
  /**
   * <code>.bilibili.app.dynamic.v2.ModuleAuthor module_author = 2;</code>
   * @return The moduleAuthor.
   */
  com.bapis.bilibili.app.dynamic.v2.ModuleAuthor getModuleAuthor();
  /**
   * <code>.bilibili.app.dynamic.v2.ModuleAuthor module_author = 2;</code>
   */
  com.bapis.bilibili.app.dynamic.v2.ModuleAuthorOrBuilder getModuleAuthorOrBuilder();

  /**
   * <code>.bilibili.app.dynamic.v2.ModuleDispute module_dispute = 3;</code>
   * @return Whether the moduleDispute field is set.
   */
  boolean hasModuleDispute();
  /**
   * <code>.bilibili.app.dynamic.v2.ModuleDispute module_dispute = 3;</code>
   * @return The moduleDispute.
   */
  com.bapis.bilibili.app.dynamic.v2.ModuleDispute getModuleDispute();
  /**
   * <code>.bilibili.app.dynamic.v2.ModuleDispute module_dispute = 3;</code>
   */
  com.bapis.bilibili.app.dynamic.v2.ModuleDisputeOrBuilder getModuleDisputeOrBuilder();

  /**
   * <code>.bilibili.app.dynamic.v2.ModuleDesc module_desc = 4;</code>
   * @return Whether the moduleDesc field is set.
   */
  boolean hasModuleDesc();
  /**
   * <code>.bilibili.app.dynamic.v2.ModuleDesc module_desc = 4;</code>
   * @return The moduleDesc.
   */
  com.bapis.bilibili.app.dynamic.v2.ModuleDesc getModuleDesc();
  /**
   * <code>.bilibili.app.dynamic.v2.ModuleDesc module_desc = 4;</code>
   */
  com.bapis.bilibili.app.dynamic.v2.ModuleDescOrBuilder getModuleDescOrBuilder();

  /**
   * <code>.bilibili.app.dynamic.v2.ModuleDynamic module_dynamic = 5;</code>
   * @return Whether the moduleDynamic field is set.
   */
  boolean hasModuleDynamic();
  /**
   * <code>.bilibili.app.dynamic.v2.ModuleDynamic module_dynamic = 5;</code>
   * @return The moduleDynamic.
   */
  com.bapis.bilibili.app.dynamic.v2.ModuleDynamic getModuleDynamic();
  /**
   * <code>.bilibili.app.dynamic.v2.ModuleDynamic module_dynamic = 5;</code>
   */
  com.bapis.bilibili.app.dynamic.v2.ModuleDynamicOrBuilder getModuleDynamicOrBuilder();

  /**
   * <code>.bilibili.app.dynamic.v2.ModuleLikeUser module_likeUser = 6;</code>
   * @return Whether the moduleLikeUser field is set.
   */
  boolean hasModuleLikeUser();
  /**
   * <code>.bilibili.app.dynamic.v2.ModuleLikeUser module_likeUser = 6;</code>
   * @return The moduleLikeUser.
   */
  com.bapis.bilibili.app.dynamic.v2.ModuleLikeUser getModuleLikeUser();
  /**
   * <code>.bilibili.app.dynamic.v2.ModuleLikeUser module_likeUser = 6;</code>
   */
  com.bapis.bilibili.app.dynamic.v2.ModuleLikeUserOrBuilder getModuleLikeUserOrBuilder();

  /**
   * <code>.bilibili.app.dynamic.v2.ModuleExtend module_extend = 7;</code>
   * @return Whether the moduleExtend field is set.
   */
  boolean hasModuleExtend();
  /**
   * <code>.bilibili.app.dynamic.v2.ModuleExtend module_extend = 7;</code>
   * @return The moduleExtend.
   */
  com.bapis.bilibili.app.dynamic.v2.ModuleExtend getModuleExtend();
  /**
   * <code>.bilibili.app.dynamic.v2.ModuleExtend module_extend = 7;</code>
   */
  com.bapis.bilibili.app.dynamic.v2.ModuleExtendOrBuilder getModuleExtendOrBuilder();

  /**
   * <code>.bilibili.app.dynamic.v2.ModuleAdditional module_additional = 8;</code>
   * @return Whether the moduleAdditional field is set.
   */
  boolean hasModuleAdditional();
  /**
   * <code>.bilibili.app.dynamic.v2.ModuleAdditional module_additional = 8;</code>
   * @return The moduleAdditional.
   */
  com.bapis.bilibili.app.dynamic.v2.ModuleAdditional getModuleAdditional();
  /**
   * <code>.bilibili.app.dynamic.v2.ModuleAdditional module_additional = 8;</code>
   */
  com.bapis.bilibili.app.dynamic.v2.ModuleAdditionalOrBuilder getModuleAdditionalOrBuilder();

  /**
   * <code>.bilibili.app.dynamic.v2.ModuleStat module_stat = 9;</code>
   * @return Whether the moduleStat field is set.
   */
  boolean hasModuleStat();
  /**
   * <code>.bilibili.app.dynamic.v2.ModuleStat module_stat = 9;</code>
   * @return The moduleStat.
   */
  com.bapis.bilibili.app.dynamic.v2.ModuleStat getModuleStat();
  /**
   * <code>.bilibili.app.dynamic.v2.ModuleStat module_stat = 9;</code>
   */
  com.bapis.bilibili.app.dynamic.v2.ModuleStatOrBuilder getModuleStatOrBuilder();

  /**
   * <code>.bilibili.app.dynamic.v2.ModuleFold module_fold = 10;</code>
   * @return Whether the moduleFold field is set.
   */
  boolean hasModuleFold();
  /**
   * <code>.bilibili.app.dynamic.v2.ModuleFold module_fold = 10;</code>
   * @return The moduleFold.
   */
  com.bapis.bilibili.app.dynamic.v2.ModuleFold getModuleFold();
  /**
   * <code>.bilibili.app.dynamic.v2.ModuleFold module_fold = 10;</code>
   */
  com.bapis.bilibili.app.dynamic.v2.ModuleFoldOrBuilder getModuleFoldOrBuilder();

  /**
   * <code>.bilibili.app.dynamic.v2.ModuleComment module_comment = 11;</code>
   * @return Whether the moduleComment field is set.
   */
  boolean hasModuleComment();
  /**
   * <code>.bilibili.app.dynamic.v2.ModuleComment module_comment = 11;</code>
   * @return The moduleComment.
   */
  com.bapis.bilibili.app.dynamic.v2.ModuleComment getModuleComment();
  /**
   * <code>.bilibili.app.dynamic.v2.ModuleComment module_comment = 11;</code>
   */
  com.bapis.bilibili.app.dynamic.v2.ModuleCommentOrBuilder getModuleCommentOrBuilder();

  public com.bapis.bilibili.app.dynamic.v2.Module.ModuleItemCase getModuleItemCase();
}
