// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/app/dynamic/v2/dynamic.proto

package com.bapis.bilibili.app.dynamic.v2;

/**
 * <pre>
 * ModuleDesc 动态-描述文字模块
 * </pre>
 *
 * Protobuf type {@code bilibili.app.dynamic.v2.ModuleDesc}
 */
public final class ModuleDesc extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bilibili.app.dynamic.v2.ModuleDesc)
    ModuleDescOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ModuleDesc.newBuilder() to construct.
  private ModuleDesc(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ModuleDesc() {
    desc_ = java.util.Collections.emptyList();
    jumpUri_ = "";
    text_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ModuleDesc();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ModuleDesc(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              desc_ = new java.util.ArrayList<com.bapis.bilibili.app.dynamic.v2.Description>();
              mutable_bitField0_ |= 0x00000001;
            }
            desc_.add(
                input.readMessage(com.bapis.bilibili.app.dynamic.v2.Description.parser(), extensionRegistry));
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            jumpUri_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            text_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        desc_ = java.util.Collections.unmodifiableList(desc_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bapis.bilibili.app.dynamic.v2.DynamicOuterClass.internal_static_bilibili_app_dynamic_v2_ModuleDesc_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bapis.bilibili.app.dynamic.v2.DynamicOuterClass.internal_static_bilibili_app_dynamic_v2_ModuleDesc_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bapis.bilibili.app.dynamic.v2.ModuleDesc.class, com.bapis.bilibili.app.dynamic.v2.ModuleDesc.Builder.class);
  }

  public static final int DESC_FIELD_NUMBER = 1;
  private java.util.List<com.bapis.bilibili.app.dynamic.v2.Description> desc_;
  /**
   * <pre>
   * 描述信息（已按高亮拆分）
   * </pre>
   *
   * <code>repeated .bilibili.app.dynamic.v2.Description desc = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.bapis.bilibili.app.dynamic.v2.Description> getDescList() {
    return desc_;
  }
  /**
   * <pre>
   * 描述信息（已按高亮拆分）
   * </pre>
   *
   * <code>repeated .bilibili.app.dynamic.v2.Description desc = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.bapis.bilibili.app.dynamic.v2.DescriptionOrBuilder> 
      getDescOrBuilderList() {
    return desc_;
  }
  /**
   * <pre>
   * 描述信息（已按高亮拆分）
   * </pre>
   *
   * <code>repeated .bilibili.app.dynamic.v2.Description desc = 1;</code>
   */
  @java.lang.Override
  public int getDescCount() {
    return desc_.size();
  }
  /**
   * <pre>
   * 描述信息（已按高亮拆分）
   * </pre>
   *
   * <code>repeated .bilibili.app.dynamic.v2.Description desc = 1;</code>
   */
  @java.lang.Override
  public com.bapis.bilibili.app.dynamic.v2.Description getDesc(int index) {
    return desc_.get(index);
  }
  /**
   * <pre>
   * 描述信息（已按高亮拆分）
   * </pre>
   *
   * <code>repeated .bilibili.app.dynamic.v2.Description desc = 1;</code>
   */
  @java.lang.Override
  public com.bapis.bilibili.app.dynamic.v2.DescriptionOrBuilder getDescOrBuilder(
      int index) {
    return desc_.get(index);
  }

  public static final int JUMP_URI_FIELD_NUMBER = 2;
  private volatile java.lang.Object jumpUri_;
  /**
   * <pre>
   * 点击跳转链接
   * </pre>
   *
   * <code>string jump_uri = 2;</code>
   * @return The jumpUri.
   */
  @java.lang.Override
  public java.lang.String getJumpUri() {
    java.lang.Object ref = jumpUri_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      jumpUri_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 点击跳转链接
   * </pre>
   *
   * <code>string jump_uri = 2;</code>
   * @return The bytes for jumpUri.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJumpUriBytes() {
    java.lang.Object ref = jumpUri_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      jumpUri_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TEXT_FIELD_NUMBER = 3;
  private volatile java.lang.Object text_;
  /**
   * <pre>
   * 文本原本
   * </pre>
   *
   * <code>string text = 3;</code>
   * @return The text.
   */
  @java.lang.Override
  public java.lang.String getText() {
    java.lang.Object ref = text_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      text_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 文本原本
   * </pre>
   *
   * <code>string text = 3;</code>
   * @return The bytes for text.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTextBytes() {
    java.lang.Object ref = text_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      text_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < desc_.size(); i++) {
      output.writeMessage(1, desc_.get(i));
    }
    if (!getJumpUriBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, jumpUri_);
    }
    if (!getTextBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, text_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < desc_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, desc_.get(i));
    }
    if (!getJumpUriBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, jumpUri_);
    }
    if (!getTextBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, text_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bapis.bilibili.app.dynamic.v2.ModuleDesc)) {
      return super.equals(obj);
    }
    com.bapis.bilibili.app.dynamic.v2.ModuleDesc other = (com.bapis.bilibili.app.dynamic.v2.ModuleDesc) obj;

    if (!getDescList()
        .equals(other.getDescList())) return false;
    if (!getJumpUri()
        .equals(other.getJumpUri())) return false;
    if (!getText()
        .equals(other.getText())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDescCount() > 0) {
      hash = (37 * hash) + DESC_FIELD_NUMBER;
      hash = (53 * hash) + getDescList().hashCode();
    }
    hash = (37 * hash) + JUMP_URI_FIELD_NUMBER;
    hash = (53 * hash) + getJumpUri().hashCode();
    hash = (37 * hash) + TEXT_FIELD_NUMBER;
    hash = (53 * hash) + getText().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bapis.bilibili.app.dynamic.v2.ModuleDesc parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bapis.bilibili.app.dynamic.v2.ModuleDesc parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bapis.bilibili.app.dynamic.v2.ModuleDesc parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bapis.bilibili.app.dynamic.v2.ModuleDesc parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bapis.bilibili.app.dynamic.v2.ModuleDesc parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bapis.bilibili.app.dynamic.v2.ModuleDesc parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bapis.bilibili.app.dynamic.v2.ModuleDesc parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bapis.bilibili.app.dynamic.v2.ModuleDesc parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bapis.bilibili.app.dynamic.v2.ModuleDesc parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bapis.bilibili.app.dynamic.v2.ModuleDesc parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bapis.bilibili.app.dynamic.v2.ModuleDesc parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bapis.bilibili.app.dynamic.v2.ModuleDesc parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bapis.bilibili.app.dynamic.v2.ModuleDesc prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ModuleDesc 动态-描述文字模块
   * </pre>
   *
   * Protobuf type {@code bilibili.app.dynamic.v2.ModuleDesc}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bilibili.app.dynamic.v2.ModuleDesc)
      com.bapis.bilibili.app.dynamic.v2.ModuleDescOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bapis.bilibili.app.dynamic.v2.DynamicOuterClass.internal_static_bilibili_app_dynamic_v2_ModuleDesc_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bapis.bilibili.app.dynamic.v2.DynamicOuterClass.internal_static_bilibili_app_dynamic_v2_ModuleDesc_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bapis.bilibili.app.dynamic.v2.ModuleDesc.class, com.bapis.bilibili.app.dynamic.v2.ModuleDesc.Builder.class);
    }

    // Construct using com.bapis.bilibili.app.dynamic.v2.ModuleDesc.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDescFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (descBuilder_ == null) {
        desc_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        descBuilder_.clear();
      }
      jumpUri_ = "";

      text_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bapis.bilibili.app.dynamic.v2.DynamicOuterClass.internal_static_bilibili_app_dynamic_v2_ModuleDesc_descriptor;
    }

    @java.lang.Override
    public com.bapis.bilibili.app.dynamic.v2.ModuleDesc getDefaultInstanceForType() {
      return com.bapis.bilibili.app.dynamic.v2.ModuleDesc.getDefaultInstance();
    }

    @java.lang.Override
    public com.bapis.bilibili.app.dynamic.v2.ModuleDesc build() {
      com.bapis.bilibili.app.dynamic.v2.ModuleDesc result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bapis.bilibili.app.dynamic.v2.ModuleDesc buildPartial() {
      com.bapis.bilibili.app.dynamic.v2.ModuleDesc result = new com.bapis.bilibili.app.dynamic.v2.ModuleDesc(this);
      int from_bitField0_ = bitField0_;
      if (descBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          desc_ = java.util.Collections.unmodifiableList(desc_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.desc_ = desc_;
      } else {
        result.desc_ = descBuilder_.build();
      }
      result.jumpUri_ = jumpUri_;
      result.text_ = text_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bapis.bilibili.app.dynamic.v2.ModuleDesc) {
        return mergeFrom((com.bapis.bilibili.app.dynamic.v2.ModuleDesc)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bapis.bilibili.app.dynamic.v2.ModuleDesc other) {
      if (other == com.bapis.bilibili.app.dynamic.v2.ModuleDesc.getDefaultInstance()) return this;
      if (descBuilder_ == null) {
        if (!other.desc_.isEmpty()) {
          if (desc_.isEmpty()) {
            desc_ = other.desc_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDescIsMutable();
            desc_.addAll(other.desc_);
          }
          onChanged();
        }
      } else {
        if (!other.desc_.isEmpty()) {
          if (descBuilder_.isEmpty()) {
            descBuilder_.dispose();
            descBuilder_ = null;
            desc_ = other.desc_;
            bitField0_ = (bitField0_ & ~0x00000001);
            descBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDescFieldBuilder() : null;
          } else {
            descBuilder_.addAllMessages(other.desc_);
          }
        }
      }
      if (!other.getJumpUri().isEmpty()) {
        jumpUri_ = other.jumpUri_;
        onChanged();
      }
      if (!other.getText().isEmpty()) {
        text_ = other.text_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bapis.bilibili.app.dynamic.v2.ModuleDesc parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bapis.bilibili.app.dynamic.v2.ModuleDesc) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.bapis.bilibili.app.dynamic.v2.Description> desc_ =
      java.util.Collections.emptyList();
    private void ensureDescIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        desc_ = new java.util.ArrayList<com.bapis.bilibili.app.dynamic.v2.Description>(desc_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.bapis.bilibili.app.dynamic.v2.Description, com.bapis.bilibili.app.dynamic.v2.Description.Builder, com.bapis.bilibili.app.dynamic.v2.DescriptionOrBuilder> descBuilder_;

    /**
     * <pre>
     * 描述信息（已按高亮拆分）
     * </pre>
     *
     * <code>repeated .bilibili.app.dynamic.v2.Description desc = 1;</code>
     */
    public java.util.List<com.bapis.bilibili.app.dynamic.v2.Description> getDescList() {
      if (descBuilder_ == null) {
        return java.util.Collections.unmodifiableList(desc_);
      } else {
        return descBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 描述信息（已按高亮拆分）
     * </pre>
     *
     * <code>repeated .bilibili.app.dynamic.v2.Description desc = 1;</code>
     */
    public int getDescCount() {
      if (descBuilder_ == null) {
        return desc_.size();
      } else {
        return descBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 描述信息（已按高亮拆分）
     * </pre>
     *
     * <code>repeated .bilibili.app.dynamic.v2.Description desc = 1;</code>
     */
    public com.bapis.bilibili.app.dynamic.v2.Description getDesc(int index) {
      if (descBuilder_ == null) {
        return desc_.get(index);
      } else {
        return descBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 描述信息（已按高亮拆分）
     * </pre>
     *
     * <code>repeated .bilibili.app.dynamic.v2.Description desc = 1;</code>
     */
    public Builder setDesc(
        int index, com.bapis.bilibili.app.dynamic.v2.Description value) {
      if (descBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDescIsMutable();
        desc_.set(index, value);
        onChanged();
      } else {
        descBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 描述信息（已按高亮拆分）
     * </pre>
     *
     * <code>repeated .bilibili.app.dynamic.v2.Description desc = 1;</code>
     */
    public Builder setDesc(
        int index, com.bapis.bilibili.app.dynamic.v2.Description.Builder builderForValue) {
      if (descBuilder_ == null) {
        ensureDescIsMutable();
        desc_.set(index, builderForValue.build());
        onChanged();
      } else {
        descBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 描述信息（已按高亮拆分）
     * </pre>
     *
     * <code>repeated .bilibili.app.dynamic.v2.Description desc = 1;</code>
     */
    public Builder addDesc(com.bapis.bilibili.app.dynamic.v2.Description value) {
      if (descBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDescIsMutable();
        desc_.add(value);
        onChanged();
      } else {
        descBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 描述信息（已按高亮拆分）
     * </pre>
     *
     * <code>repeated .bilibili.app.dynamic.v2.Description desc = 1;</code>
     */
    public Builder addDesc(
        int index, com.bapis.bilibili.app.dynamic.v2.Description value) {
      if (descBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDescIsMutable();
        desc_.add(index, value);
        onChanged();
      } else {
        descBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 描述信息（已按高亮拆分）
     * </pre>
     *
     * <code>repeated .bilibili.app.dynamic.v2.Description desc = 1;</code>
     */
    public Builder addDesc(
        com.bapis.bilibili.app.dynamic.v2.Description.Builder builderForValue) {
      if (descBuilder_ == null) {
        ensureDescIsMutable();
        desc_.add(builderForValue.build());
        onChanged();
      } else {
        descBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 描述信息（已按高亮拆分）
     * </pre>
     *
     * <code>repeated .bilibili.app.dynamic.v2.Description desc = 1;</code>
     */
    public Builder addDesc(
        int index, com.bapis.bilibili.app.dynamic.v2.Description.Builder builderForValue) {
      if (descBuilder_ == null) {
        ensureDescIsMutable();
        desc_.add(index, builderForValue.build());
        onChanged();
      } else {
        descBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 描述信息（已按高亮拆分）
     * </pre>
     *
     * <code>repeated .bilibili.app.dynamic.v2.Description desc = 1;</code>
     */
    public Builder addAllDesc(
        java.lang.Iterable<? extends com.bapis.bilibili.app.dynamic.v2.Description> values) {
      if (descBuilder_ == null) {
        ensureDescIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, desc_);
        onChanged();
      } else {
        descBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 描述信息（已按高亮拆分）
     * </pre>
     *
     * <code>repeated .bilibili.app.dynamic.v2.Description desc = 1;</code>
     */
    public Builder clearDesc() {
      if (descBuilder_ == null) {
        desc_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        descBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 描述信息（已按高亮拆分）
     * </pre>
     *
     * <code>repeated .bilibili.app.dynamic.v2.Description desc = 1;</code>
     */
    public Builder removeDesc(int index) {
      if (descBuilder_ == null) {
        ensureDescIsMutable();
        desc_.remove(index);
        onChanged();
      } else {
        descBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 描述信息（已按高亮拆分）
     * </pre>
     *
     * <code>repeated .bilibili.app.dynamic.v2.Description desc = 1;</code>
     */
    public com.bapis.bilibili.app.dynamic.v2.Description.Builder getDescBuilder(
        int index) {
      return getDescFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 描述信息（已按高亮拆分）
     * </pre>
     *
     * <code>repeated .bilibili.app.dynamic.v2.Description desc = 1;</code>
     */
    public com.bapis.bilibili.app.dynamic.v2.DescriptionOrBuilder getDescOrBuilder(
        int index) {
      if (descBuilder_ == null) {
        return desc_.get(index);  } else {
        return descBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 描述信息（已按高亮拆分）
     * </pre>
     *
     * <code>repeated .bilibili.app.dynamic.v2.Description desc = 1;</code>
     */
    public java.util.List<? extends com.bapis.bilibili.app.dynamic.v2.DescriptionOrBuilder> 
         getDescOrBuilderList() {
      if (descBuilder_ != null) {
        return descBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(desc_);
      }
    }
    /**
     * <pre>
     * 描述信息（已按高亮拆分）
     * </pre>
     *
     * <code>repeated .bilibili.app.dynamic.v2.Description desc = 1;</code>
     */
    public com.bapis.bilibili.app.dynamic.v2.Description.Builder addDescBuilder() {
      return getDescFieldBuilder().addBuilder(
          com.bapis.bilibili.app.dynamic.v2.Description.getDefaultInstance());
    }
    /**
     * <pre>
     * 描述信息（已按高亮拆分）
     * </pre>
     *
     * <code>repeated .bilibili.app.dynamic.v2.Description desc = 1;</code>
     */
    public com.bapis.bilibili.app.dynamic.v2.Description.Builder addDescBuilder(
        int index) {
      return getDescFieldBuilder().addBuilder(
          index, com.bapis.bilibili.app.dynamic.v2.Description.getDefaultInstance());
    }
    /**
     * <pre>
     * 描述信息（已按高亮拆分）
     * </pre>
     *
     * <code>repeated .bilibili.app.dynamic.v2.Description desc = 1;</code>
     */
    public java.util.List<com.bapis.bilibili.app.dynamic.v2.Description.Builder> 
         getDescBuilderList() {
      return getDescFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.bapis.bilibili.app.dynamic.v2.Description, com.bapis.bilibili.app.dynamic.v2.Description.Builder, com.bapis.bilibili.app.dynamic.v2.DescriptionOrBuilder> 
        getDescFieldBuilder() {
      if (descBuilder_ == null) {
        descBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.bapis.bilibili.app.dynamic.v2.Description, com.bapis.bilibili.app.dynamic.v2.Description.Builder, com.bapis.bilibili.app.dynamic.v2.DescriptionOrBuilder>(
                desc_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        desc_ = null;
      }
      return descBuilder_;
    }

    private java.lang.Object jumpUri_ = "";
    /**
     * <pre>
     * 点击跳转链接
     * </pre>
     *
     * <code>string jump_uri = 2;</code>
     * @return The jumpUri.
     */
    public java.lang.String getJumpUri() {
      java.lang.Object ref = jumpUri_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jumpUri_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 点击跳转链接
     * </pre>
     *
     * <code>string jump_uri = 2;</code>
     * @return The bytes for jumpUri.
     */
    public com.google.protobuf.ByteString
        getJumpUriBytes() {
      java.lang.Object ref = jumpUri_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jumpUri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 点击跳转链接
     * </pre>
     *
     * <code>string jump_uri = 2;</code>
     * @param value The jumpUri to set.
     * @return This builder for chaining.
     */
    public Builder setJumpUri(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      jumpUri_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 点击跳转链接
     * </pre>
     *
     * <code>string jump_uri = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearJumpUri() {
      
      jumpUri_ = getDefaultInstance().getJumpUri();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 点击跳转链接
     * </pre>
     *
     * <code>string jump_uri = 2;</code>
     * @param value The bytes for jumpUri to set.
     * @return This builder for chaining.
     */
    public Builder setJumpUriBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      jumpUri_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object text_ = "";
    /**
     * <pre>
     * 文本原本
     * </pre>
     *
     * <code>string text = 3;</code>
     * @return The text.
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 文本原本
     * </pre>
     *
     * <code>string text = 3;</code>
     * @return The bytes for text.
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 文本原本
     * </pre>
     *
     * <code>string text = 3;</code>
     * @param value The text to set.
     * @return This builder for chaining.
     */
    public Builder setText(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      text_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 文本原本
     * </pre>
     *
     * <code>string text = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearText() {
      
      text_ = getDefaultInstance().getText();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 文本原本
     * </pre>
     *
     * <code>string text = 3;</code>
     * @param value The bytes for text to set.
     * @return This builder for chaining.
     */
    public Builder setTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      text_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bilibili.app.dynamic.v2.ModuleDesc)
  }

  // @@protoc_insertion_point(class_scope:bilibili.app.dynamic.v2.ModuleDesc)
  private static final com.bapis.bilibili.app.dynamic.v2.ModuleDesc DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bapis.bilibili.app.dynamic.v2.ModuleDesc();
  }

  public static com.bapis.bilibili.app.dynamic.v2.ModuleDesc getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ModuleDesc>
      PARSER = new com.google.protobuf.AbstractParser<ModuleDesc>() {
    @java.lang.Override
    public ModuleDesc parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ModuleDesc(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ModuleDesc> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ModuleDesc> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bapis.bilibili.app.dynamic.v2.ModuleDesc getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

