// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/app/dynamic/v2/dynamic.proto

package com.bapis.bilibili.app.dynamic.v2;

public interface ModuleExtendItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bilibili.app.dynamic.v2.ModuleExtendItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 类型
   * </pre>
   *
   * <code>.bilibili.app.dynamic.v2.DynExtendType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <pre>
   * 类型
   * </pre>
   *
   * <code>.bilibili.app.dynamic.v2.DynExtendType type = 1;</code>
   * @return The type.
   */
  com.bapis.bilibili.app.dynamic.v2.DynExtendType getType();

  /**
   * <code>.bilibili.app.dynamic.v2.ExtInfoTopic ext_info_topic = 2;</code>
   * @return Whether the extInfoTopic field is set.
   */
  boolean hasExtInfoTopic();
  /**
   * <code>.bilibili.app.dynamic.v2.ExtInfoTopic ext_info_topic = 2;</code>
   * @return The extInfoTopic.
   */
  com.bapis.bilibili.app.dynamic.v2.ExtInfoTopic getExtInfoTopic();
  /**
   * <code>.bilibili.app.dynamic.v2.ExtInfoTopic ext_info_topic = 2;</code>
   */
  com.bapis.bilibili.app.dynamic.v2.ExtInfoTopicOrBuilder getExtInfoTopicOrBuilder();

  /**
   * <code>.bilibili.app.dynamic.v2.ExtInfoLBS ext_info_lbs = 3;</code>
   * @return Whether the extInfoLbs field is set.
   */
  boolean hasExtInfoLbs();
  /**
   * <code>.bilibili.app.dynamic.v2.ExtInfoLBS ext_info_lbs = 3;</code>
   * @return The extInfoLbs.
   */
  com.bapis.bilibili.app.dynamic.v2.ExtInfoLBS getExtInfoLbs();
  /**
   * <code>.bilibili.app.dynamic.v2.ExtInfoLBS ext_info_lbs = 3;</code>
   */
  com.bapis.bilibili.app.dynamic.v2.ExtInfoLBSOrBuilder getExtInfoLbsOrBuilder();

  /**
   * <code>.bilibili.app.dynamic.v2.ExtInfoHot ext_info_hot = 4;</code>
   * @return Whether the extInfoHot field is set.
   */
  boolean hasExtInfoHot();
  /**
   * <code>.bilibili.app.dynamic.v2.ExtInfoHot ext_info_hot = 4;</code>
   * @return The extInfoHot.
   */
  com.bapis.bilibili.app.dynamic.v2.ExtInfoHot getExtInfoHot();
  /**
   * <code>.bilibili.app.dynamic.v2.ExtInfoHot ext_info_hot = 4;</code>
   */
  com.bapis.bilibili.app.dynamic.v2.ExtInfoHotOrBuilder getExtInfoHotOrBuilder();

  /**
   * <code>.bilibili.app.dynamic.v2.ExtInfoGame ext_info_game = 5;</code>
   * @return Whether the extInfoGame field is set.
   */
  boolean hasExtInfoGame();
  /**
   * <code>.bilibili.app.dynamic.v2.ExtInfoGame ext_info_game = 5;</code>
   * @return The extInfoGame.
   */
  com.bapis.bilibili.app.dynamic.v2.ExtInfoGame getExtInfoGame();
  /**
   * <code>.bilibili.app.dynamic.v2.ExtInfoGame ext_info_game = 5;</code>
   */
  com.bapis.bilibili.app.dynamic.v2.ExtInfoGameOrBuilder getExtInfoGameOrBuilder();

  public com.bapis.bilibili.app.dynamic.v2.ModuleExtendItem.ExtendCase getExtendCase();
}
