// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/app/dynamic/v2/dynamic.proto

package com.bapis.bilibili.app.dynamic.v2;

/**
 * <pre>
 * PlayurlParam 秒开通用参数
 * </pre>
 *
 * Protobuf type {@code bilibili.app.dynamic.v2.PlayurlParam}
 */
public final class PlayurlParam extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bilibili.app.dynamic.v2.PlayurlParam)
    PlayurlParamOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PlayurlParam.newBuilder() to construct.
  private PlayurlParam(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PlayurlParam() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PlayurlParam();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PlayurlParam(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            qn_ = input.readInt32();
            break;
          }
          case 16: {

            fnver_ = input.readInt32();
            break;
          }
          case 24: {

            fnval_ = input.readInt32();
            break;
          }
          case 32: {

            forceHost_ = input.readInt32();
            break;
          }
          case 40: {

            fourk_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bapis.bilibili.app.dynamic.v2.DynamicOuterClass.internal_static_bilibili_app_dynamic_v2_PlayurlParam_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bapis.bilibili.app.dynamic.v2.DynamicOuterClass.internal_static_bilibili_app_dynamic_v2_PlayurlParam_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bapis.bilibili.app.dynamic.v2.PlayurlParam.class, com.bapis.bilibili.app.dynamic.v2.PlayurlParam.Builder.class);
  }

  public static final int QN_FIELD_NUMBER = 1;
  private int qn_;
  /**
   * <pre>
   * 秒开清晰度（秒开用）
   * </pre>
   *
   * <code>int32 qn = 1;</code>
   * @return The qn.
   */
  @java.lang.Override
  public int getQn() {
    return qn_;
  }

  public static final int FNVER_FIELD_NUMBER = 2;
  private int fnver_;
  /**
   * <pre>
   * 功能版本号（秒开用）
   * </pre>
   *
   * <code>int32 fnver = 2;</code>
   * @return The fnver.
   */
  @java.lang.Override
  public int getFnver() {
    return fnver_;
  }

  public static final int FNVAL_FIELD_NUMBER = 3;
  private int fnval_;
  /**
   * <pre>
   * 功能标识（秒开用）
   * </pre>
   *
   * <code>int32 fnval = 3;</code>
   * @return The fnval.
   */
  @java.lang.Override
  public int getFnval() {
    return fnval_;
  }

  public static final int FORCE_HOST_FIELD_NUMBER = 4;
  private int forceHost_;
  /**
   * <pre>
   * 返回url是否强制使用域名（秒开用）
   * </pre>
   *
   * <code>int32 force_host = 4;</code>
   * @return The forceHost.
   */
  @java.lang.Override
  public int getForceHost() {
    return forceHost_;
  }

  public static final int FOURK_FIELD_NUMBER = 5;
  private int fourk_;
  /**
   * <pre>
   * 是否需要4k视频，fourk=1 表示需要，其他表示不需要（秒开用）
   * </pre>
   *
   * <code>int32 fourk = 5;</code>
   * @return The fourk.
   */
  @java.lang.Override
  public int getFourk() {
    return fourk_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (qn_ != 0) {
      output.writeInt32(1, qn_);
    }
    if (fnver_ != 0) {
      output.writeInt32(2, fnver_);
    }
    if (fnval_ != 0) {
      output.writeInt32(3, fnval_);
    }
    if (forceHost_ != 0) {
      output.writeInt32(4, forceHost_);
    }
    if (fourk_ != 0) {
      output.writeInt32(5, fourk_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (qn_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, qn_);
    }
    if (fnver_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, fnver_);
    }
    if (fnval_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, fnval_);
    }
    if (forceHost_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, forceHost_);
    }
    if (fourk_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, fourk_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bapis.bilibili.app.dynamic.v2.PlayurlParam)) {
      return super.equals(obj);
    }
    com.bapis.bilibili.app.dynamic.v2.PlayurlParam other = (com.bapis.bilibili.app.dynamic.v2.PlayurlParam) obj;

    if (getQn()
        != other.getQn()) return false;
    if (getFnver()
        != other.getFnver()) return false;
    if (getFnval()
        != other.getFnval()) return false;
    if (getForceHost()
        != other.getForceHost()) return false;
    if (getFourk()
        != other.getFourk()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + QN_FIELD_NUMBER;
    hash = (53 * hash) + getQn();
    hash = (37 * hash) + FNVER_FIELD_NUMBER;
    hash = (53 * hash) + getFnver();
    hash = (37 * hash) + FNVAL_FIELD_NUMBER;
    hash = (53 * hash) + getFnval();
    hash = (37 * hash) + FORCE_HOST_FIELD_NUMBER;
    hash = (53 * hash) + getForceHost();
    hash = (37 * hash) + FOURK_FIELD_NUMBER;
    hash = (53 * hash) + getFourk();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bapis.bilibili.app.dynamic.v2.PlayurlParam parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bapis.bilibili.app.dynamic.v2.PlayurlParam parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bapis.bilibili.app.dynamic.v2.PlayurlParam parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bapis.bilibili.app.dynamic.v2.PlayurlParam parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bapis.bilibili.app.dynamic.v2.PlayurlParam parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bapis.bilibili.app.dynamic.v2.PlayurlParam parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bapis.bilibili.app.dynamic.v2.PlayurlParam parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bapis.bilibili.app.dynamic.v2.PlayurlParam parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bapis.bilibili.app.dynamic.v2.PlayurlParam parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bapis.bilibili.app.dynamic.v2.PlayurlParam parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bapis.bilibili.app.dynamic.v2.PlayurlParam parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bapis.bilibili.app.dynamic.v2.PlayurlParam parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bapis.bilibili.app.dynamic.v2.PlayurlParam prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * PlayurlParam 秒开通用参数
   * </pre>
   *
   * Protobuf type {@code bilibili.app.dynamic.v2.PlayurlParam}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bilibili.app.dynamic.v2.PlayurlParam)
      com.bapis.bilibili.app.dynamic.v2.PlayurlParamOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bapis.bilibili.app.dynamic.v2.DynamicOuterClass.internal_static_bilibili_app_dynamic_v2_PlayurlParam_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bapis.bilibili.app.dynamic.v2.DynamicOuterClass.internal_static_bilibili_app_dynamic_v2_PlayurlParam_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bapis.bilibili.app.dynamic.v2.PlayurlParam.class, com.bapis.bilibili.app.dynamic.v2.PlayurlParam.Builder.class);
    }

    // Construct using com.bapis.bilibili.app.dynamic.v2.PlayurlParam.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      qn_ = 0;

      fnver_ = 0;

      fnval_ = 0;

      forceHost_ = 0;

      fourk_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bapis.bilibili.app.dynamic.v2.DynamicOuterClass.internal_static_bilibili_app_dynamic_v2_PlayurlParam_descriptor;
    }

    @java.lang.Override
    public com.bapis.bilibili.app.dynamic.v2.PlayurlParam getDefaultInstanceForType() {
      return com.bapis.bilibili.app.dynamic.v2.PlayurlParam.getDefaultInstance();
    }

    @java.lang.Override
    public com.bapis.bilibili.app.dynamic.v2.PlayurlParam build() {
      com.bapis.bilibili.app.dynamic.v2.PlayurlParam result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bapis.bilibili.app.dynamic.v2.PlayurlParam buildPartial() {
      com.bapis.bilibili.app.dynamic.v2.PlayurlParam result = new com.bapis.bilibili.app.dynamic.v2.PlayurlParam(this);
      result.qn_ = qn_;
      result.fnver_ = fnver_;
      result.fnval_ = fnval_;
      result.forceHost_ = forceHost_;
      result.fourk_ = fourk_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bapis.bilibili.app.dynamic.v2.PlayurlParam) {
        return mergeFrom((com.bapis.bilibili.app.dynamic.v2.PlayurlParam)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bapis.bilibili.app.dynamic.v2.PlayurlParam other) {
      if (other == com.bapis.bilibili.app.dynamic.v2.PlayurlParam.getDefaultInstance()) return this;
      if (other.getQn() != 0) {
        setQn(other.getQn());
      }
      if (other.getFnver() != 0) {
        setFnver(other.getFnver());
      }
      if (other.getFnval() != 0) {
        setFnval(other.getFnval());
      }
      if (other.getForceHost() != 0) {
        setForceHost(other.getForceHost());
      }
      if (other.getFourk() != 0) {
        setFourk(other.getFourk());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bapis.bilibili.app.dynamic.v2.PlayurlParam parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bapis.bilibili.app.dynamic.v2.PlayurlParam) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int qn_ ;
    /**
     * <pre>
     * 秒开清晰度（秒开用）
     * </pre>
     *
     * <code>int32 qn = 1;</code>
     * @return The qn.
     */
    @java.lang.Override
    public int getQn() {
      return qn_;
    }
    /**
     * <pre>
     * 秒开清晰度（秒开用）
     * </pre>
     *
     * <code>int32 qn = 1;</code>
     * @param value The qn to set.
     * @return This builder for chaining.
     */
    public Builder setQn(int value) {
      
      qn_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 秒开清晰度（秒开用）
     * </pre>
     *
     * <code>int32 qn = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearQn() {
      
      qn_ = 0;
      onChanged();
      return this;
    }

    private int fnver_ ;
    /**
     * <pre>
     * 功能版本号（秒开用）
     * </pre>
     *
     * <code>int32 fnver = 2;</code>
     * @return The fnver.
     */
    @java.lang.Override
    public int getFnver() {
      return fnver_;
    }
    /**
     * <pre>
     * 功能版本号（秒开用）
     * </pre>
     *
     * <code>int32 fnver = 2;</code>
     * @param value The fnver to set.
     * @return This builder for chaining.
     */
    public Builder setFnver(int value) {
      
      fnver_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 功能版本号（秒开用）
     * </pre>
     *
     * <code>int32 fnver = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFnver() {
      
      fnver_ = 0;
      onChanged();
      return this;
    }

    private int fnval_ ;
    /**
     * <pre>
     * 功能标识（秒开用）
     * </pre>
     *
     * <code>int32 fnval = 3;</code>
     * @return The fnval.
     */
    @java.lang.Override
    public int getFnval() {
      return fnval_;
    }
    /**
     * <pre>
     * 功能标识（秒开用）
     * </pre>
     *
     * <code>int32 fnval = 3;</code>
     * @param value The fnval to set.
     * @return This builder for chaining.
     */
    public Builder setFnval(int value) {
      
      fnval_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 功能标识（秒开用）
     * </pre>
     *
     * <code>int32 fnval = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFnval() {
      
      fnval_ = 0;
      onChanged();
      return this;
    }

    private int forceHost_ ;
    /**
     * <pre>
     * 返回url是否强制使用域名（秒开用）
     * </pre>
     *
     * <code>int32 force_host = 4;</code>
     * @return The forceHost.
     */
    @java.lang.Override
    public int getForceHost() {
      return forceHost_;
    }
    /**
     * <pre>
     * 返回url是否强制使用域名（秒开用）
     * </pre>
     *
     * <code>int32 force_host = 4;</code>
     * @param value The forceHost to set.
     * @return This builder for chaining.
     */
    public Builder setForceHost(int value) {
      
      forceHost_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 返回url是否强制使用域名（秒开用）
     * </pre>
     *
     * <code>int32 force_host = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearForceHost() {
      
      forceHost_ = 0;
      onChanged();
      return this;
    }

    private int fourk_ ;
    /**
     * <pre>
     * 是否需要4k视频，fourk=1 表示需要，其他表示不需要（秒开用）
     * </pre>
     *
     * <code>int32 fourk = 5;</code>
     * @return The fourk.
     */
    @java.lang.Override
    public int getFourk() {
      return fourk_;
    }
    /**
     * <pre>
     * 是否需要4k视频，fourk=1 表示需要，其他表示不需要（秒开用）
     * </pre>
     *
     * <code>int32 fourk = 5;</code>
     * @param value The fourk to set.
     * @return This builder for chaining.
     */
    public Builder setFourk(int value) {
      
      fourk_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否需要4k视频，fourk=1 表示需要，其他表示不需要（秒开用）
     * </pre>
     *
     * <code>int32 fourk = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearFourk() {
      
      fourk_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bilibili.app.dynamic.v2.PlayurlParam)
  }

  // @@protoc_insertion_point(class_scope:bilibili.app.dynamic.v2.PlayurlParam)
  private static final com.bapis.bilibili.app.dynamic.v2.PlayurlParam DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bapis.bilibili.app.dynamic.v2.PlayurlParam();
  }

  public static com.bapis.bilibili.app.dynamic.v2.PlayurlParam getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PlayurlParam>
      PARSER = new com.google.protobuf.AbstractParser<PlayurlParam>() {
    @java.lang.Override
    public PlayurlParam parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PlayurlParam(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PlayurlParam> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PlayurlParam> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bapis.bilibili.app.dynamic.v2.PlayurlParam getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

