// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/app/dynamic/v2/dynamic.proto

package com.bapis.bilibili.app.dynamic.v2;

/**
 * <pre>
 * ThreePointAttentionStatus 枚举-三点关注状态
 * </pre>
 *
 * Protobuf enum {@code bilibili.app.dynamic.v2.ThreePointAttentionStatus}
 */
public enum ThreePointAttentionStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>tp_not_attention = 0;</code>
   */
  tp_not_attention(0),
  /**
   * <code>tp_attention = 1;</code>
   */
  tp_attention(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>tp_not_attention = 0;</code>
   */
  public static final int tp_not_attention_VALUE = 0;
  /**
   * <code>tp_attention = 1;</code>
   */
  public static final int tp_attention_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ThreePointAttentionStatus valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ThreePointAttentionStatus forNumber(int value) {
    switch (value) {
      case 0: return tp_not_attention;
      case 1: return tp_attention;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ThreePointAttentionStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ThreePointAttentionStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ThreePointAttentionStatus>() {
          public ThreePointAttentionStatus findValueByNumber(int number) {
            return ThreePointAttentionStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.bapis.bilibili.app.dynamic.v2.DynamicOuterClass.getDescriptor().getEnumTypes().get(12);
  }

  private static final ThreePointAttentionStatus[] VALUES = values();

  public static ThreePointAttentionStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ThreePointAttentionStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:bilibili.app.dynamic.v2.ThreePointAttentionStatus)
}

