// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bilibili/app/dynamic/v2/dynamic.proto

package com.bapis.bilibili.app.dynamic.v2;

public interface ThreePointShareChannelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bilibili.app.dynamic.v2.ThreePointShareChannel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * icon
   * </pre>
   *
   * <code>string icon = 1;</code>
   * @return The icon.
   */
  java.lang.String getIcon();
  /**
   * <pre>
   * icon
   * </pre>
   *
   * <code>string icon = 1;</code>
   * @return The bytes for icon.
   */
  com.google.protobuf.ByteString
      getIconBytes();

  /**
   * <pre>
   * 名称
   * </pre>
   *
   * <code>string title = 2;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <pre>
   * 名称
   * </pre>
   *
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();
}
